
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model AvatarPicture
 * 
 */
export type AvatarPicture = Prisma.AvatarPictureModel
/**
 * Model CoverPicture
 * 
 */
export type CoverPicture = Prisma.CoverPictureModel
/**
 * Model Profile
 * 
 */
export type Profile = Prisma.ProfileModel
/**
 * Model AnimeBookmark
 * 
 */
export type AnimeBookmark = Prisma.AnimeBookmarkModel
/**
 * Model AnimeFavorite
 * 
 */
export type AnimeFavorite = Prisma.AnimeFavoriteModel
/**
 * Model Reply
 * 
 */
export type Reply = Prisma.ReplyModel
/**
 * Model Comment
 * 
 */
export type Comment = Prisma.CommentModel
/**
 * Model CommentVote
 * 
 */
export type CommentVote = Prisma.CommentVoteModel
/**
 * Model ReplyVote
 * 
 */
export type ReplyVote = Prisma.ReplyVoteModel
