
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/library"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Accounts
 * const accounts = await prisma.account.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }


// file annotations for bundling tools to include these files
path.join(__dirname, "libquery_engine-debian-openssl-3.0.x.so.node")
path.join(process.cwd(), "src/databases/orm/libquery_engine-debian-openssl-3.0.x.so.node")

/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model AvatarPicture
 * 
 */
export type AvatarPicture = Prisma.AvatarPictureModel
/**
 * Model CoverPicture
 * 
 */
export type CoverPicture = Prisma.CoverPictureModel
/**
 * Model Profile
 * 
 */
export type Profile = Prisma.ProfileModel
/**
 * Model AnimeBookmark
 * 
 */
export type AnimeBookmark = Prisma.AnimeBookmarkModel
/**
 * Model AnimeFavorite
 * 
 */
export type AnimeFavorite = Prisma.AnimeFavoriteModel
/**
 * Model Reply
 * 
 */
export type Reply = Prisma.ReplyModel
/**
 * Model Comment
 * 
 */
export type Comment = Prisma.CommentModel
/**
 * Model CommentVote
 * 
 */
export type CommentVote = Prisma.CommentVoteModel
/**
 * Model ReplyVote
 * 
 */
export type ReplyVote = Prisma.ReplyVoteModel

export type AnimeStatus = $Enums.AnimeStatus
export const AnimeStatus = $Enums.AnimeStatus

export type AccountType = $Enums.AccountType
export const AccountType = $Enums.AccountType
