
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AnimeStatus = {
  WATCHING: 'WATCHING',
  ABANDONED: 'ABANDONED',
  PLANNED: 'PLANNED',
  COMPLETED: 'COMPLETED'
} as const

export type AnimeStatus = (typeof AnimeStatus)[keyof typeof AnimeStatus]


export const AccountType = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  DEVELOPER: 'DEVELOPER',
  TESTER: 'TESTER'
} as const

export type AccountType = (typeof AccountType)[keyof typeof AccountType]
