export const ResponseCode = {
    OK: "OK",
    CREATED: "CREATED",
    ACCEPTED: "ACCEPTED",
    BAD_REQUEST: "BAD_REQUEST",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    BAD_GATEWAY: "BAD_GATEWAY",
    PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
    TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
    NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
    UNEXPECTED_INTERNAL_ERROR: "UNEXPECTED_INTERNAL_ERROR",
    EXPECTED_INTERNAL_ERROR: "EXPECTED_INTERNAL_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    I_AM_A_TEAPOT: "I_AM_A_TEAPOT",
} as const;
export type ResponseCode = (typeof ResponseCode)[keyof typeof ResponseCode];

export const UserServiceResponseStatusCodes = {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    PAYLOAD_TOO_LARGE: 413,
    TOO_MANY_REQUESTS: 429,
    NOT_IMPLEMENTED: 501,
    UNEXPECTED_INTERNAL_ERROR: 500,
    EXPECTED_INTERNAL_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
    MEDIA_SERVICE_NOT_AVAILABLE: 503,
    MEDIA_SERVICE_ERROR: 503,
    BAD_GATEWAY: 502,
    I_AM_A_TEAPOT: 418,
} as const;

export type I_UserServiceResponseStatusCodes = (typeof UserServiceResponseStatusCodes)[keyof typeof UserServiceResponseStatusCodes];
