/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck
/*
 * This file exports the `AnimeFavorite` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model AnimeFavorite
 *
 */
export type AnimeFavoriteModel = runtime.Types.Result.DefaultSelection<Prisma.$AnimeFavoritePayload>;

export type AggregateAnimeFavorite = {
    _count: AnimeFavoriteCountAggregateOutputType | null;
    _avg: AnimeFavoriteAvgAggregateOutputType | null;
    _sum: AnimeFavoriteSumAggregateOutputType | null;
    _min: AnimeFavoriteMinAggregateOutputType | null;
    _max: AnimeFavoriteMaxAggregateOutputType | null;
};

export type AnimeFavoriteAvgAggregateOutputType = {
    anime_id: number | null;
};

export type AnimeFavoriteSumAggregateOutputType = {
    anime_id: number | null;
};

export type AnimeFavoriteMinAggregateOutputType = {
    id: string | null;
    created_at: Date | null;
    updated_at: Date | null;
    profile_id: string | null;
    anime_id: number | null;
    vote: boolean | null;
};

export type AnimeFavoriteMaxAggregateOutputType = {
    id: string | null;
    created_at: Date | null;
    updated_at: Date | null;
    profile_id: string | null;
    anime_id: number | null;
    vote: boolean | null;
};

export type AnimeFavoriteCountAggregateOutputType = {
    id: number;
    created_at: number;
    updated_at: number;
    profile_id: number;
    anime_id: number;
    vote: number;
    _all: number;
};

export type AnimeFavoriteAvgAggregateInputType = {
    anime_id?: true;
};

export type AnimeFavoriteSumAggregateInputType = {
    anime_id?: true;
};

export type AnimeFavoriteMinAggregateInputType = {
    id?: true;
    created_at?: true;
    updated_at?: true;
    profile_id?: true;
    anime_id?: true;
    vote?: true;
};

export type AnimeFavoriteMaxAggregateInputType = {
    id?: true;
    created_at?: true;
    updated_at?: true;
    profile_id?: true;
    anime_id?: true;
    vote?: true;
};

export type AnimeFavoriteCountAggregateInputType = {
    id?: true;
    created_at?: true;
    updated_at?: true;
    profile_id?: true;
    anime_id?: true;
    vote?: true;
    _all?: true;
};

export type AnimeFavoriteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Filter which AnimeFavorite to aggregate.
     */
    where?: Prisma.AnimeFavoriteWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of AnimeFavorites to fetch.
     */
    orderBy?: Prisma.AnimeFavoriteOrderByWithRelationInput | Prisma.AnimeFavoriteOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.AnimeFavoriteWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` AnimeFavorites from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` AnimeFavorites.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned AnimeFavorites
     **/
    _count?: true | AnimeFavoriteCountAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to average
     **/
    _avg?: AnimeFavoriteAvgAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to sum
     **/
    _sum?: AnimeFavoriteSumAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: AnimeFavoriteMinAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: AnimeFavoriteMaxAggregateInputType;
};

export type GetAnimeFavoriteAggregateType<T extends AnimeFavoriteAggregateArgs> = {
    [P in keyof T & keyof AggregateAnimeFavorite]: P extends "_count" | "count"
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateAnimeFavorite[P]>
        : Prisma.GetScalarType<T[P], AggregateAnimeFavorite[P]>;
};

export type AnimeFavoriteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    where?: Prisma.AnimeFavoriteWhereInput;
    orderBy?: Prisma.AnimeFavoriteOrderByWithAggregationInput | Prisma.AnimeFavoriteOrderByWithAggregationInput[];
    by: Prisma.AnimeFavoriteScalarFieldEnum[] | Prisma.AnimeFavoriteScalarFieldEnum;
    having?: Prisma.AnimeFavoriteScalarWhereWithAggregatesInput;
    take?: number;
    skip?: number;
    _count?: AnimeFavoriteCountAggregateInputType | true;
    _avg?: AnimeFavoriteAvgAggregateInputType;
    _sum?: AnimeFavoriteSumAggregateInputType;
    _min?: AnimeFavoriteMinAggregateInputType;
    _max?: AnimeFavoriteMaxAggregateInputType;
};

export type AnimeFavoriteGroupByOutputType = {
    id: string;
    created_at: Date;
    updated_at: Date;
    profile_id: string;
    anime_id: number;
    vote: boolean;
    _count: AnimeFavoriteCountAggregateOutputType | null;
    _avg: AnimeFavoriteAvgAggregateOutputType | null;
    _sum: AnimeFavoriteSumAggregateOutputType | null;
    _min: AnimeFavoriteMinAggregateOutputType | null;
    _max: AnimeFavoriteMaxAggregateOutputType | null;
};

type GetAnimeFavoriteGroupByPayload<T extends AnimeFavoriteGroupByArgs> = Prisma.PrismaPromise<
    Array<
        Prisma.PickEnumerable<AnimeFavoriteGroupByOutputType, T["by"]> & {
            [P in keyof T & keyof AnimeFavoriteGroupByOutputType]: P extends "_count"
                ? T[P] extends boolean
                    ? number
                    : Prisma.GetScalarType<T[P], AnimeFavoriteGroupByOutputType[P]>
                : Prisma.GetScalarType<T[P], AnimeFavoriteGroupByOutputType[P]>;
        }
    >
>;

export type AnimeFavoriteWhereInput = {
    AND?: Prisma.AnimeFavoriteWhereInput | Prisma.AnimeFavoriteWhereInput[];
    OR?: Prisma.AnimeFavoriteWhereInput[];
    NOT?: Prisma.AnimeFavoriteWhereInput | Prisma.AnimeFavoriteWhereInput[];
    id?: Prisma.StringFilter<"AnimeFavorite"> | string;
    created_at?: Prisma.DateTimeFilter<"AnimeFavorite"> | Date | string;
    updated_at?: Prisma.DateTimeFilter<"AnimeFavorite"> | Date | string;
    profile_id?: Prisma.StringFilter<"AnimeFavorite"> | string;
    anime_id?: Prisma.IntFilter<"AnimeFavorite"> | number;
    vote?: Prisma.BoolFilter<"AnimeFavorite"> | boolean;
    profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>;
};

export type AnimeFavoriteOrderByWithRelationInput = {
    id?: Prisma.SortOrder;
    created_at?: Prisma.SortOrder;
    updated_at?: Prisma.SortOrder;
    profile_id?: Prisma.SortOrder;
    anime_id?: Prisma.SortOrder;
    vote?: Prisma.SortOrder;
    profile?: Prisma.ProfileOrderByWithRelationInput;
};

export type AnimeFavoriteWhereUniqueInput = Prisma.AtLeast<
    {
        id?: string;
        profile_id_anime_id?: Prisma.AnimeFavoriteProfile_idAnime_idCompoundUniqueInput;
        AND?: Prisma.AnimeFavoriteWhereInput | Prisma.AnimeFavoriteWhereInput[];
        OR?: Prisma.AnimeFavoriteWhereInput[];
        NOT?: Prisma.AnimeFavoriteWhereInput | Prisma.AnimeFavoriteWhereInput[];
        created_at?: Prisma.DateTimeFilter<"AnimeFavorite"> | Date | string;
        updated_at?: Prisma.DateTimeFilter<"AnimeFavorite"> | Date | string;
        profile_id?: Prisma.StringFilter<"AnimeFavorite"> | string;
        anime_id?: Prisma.IntFilter<"AnimeFavorite"> | number;
        vote?: Prisma.BoolFilter<"AnimeFavorite"> | boolean;
        profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>;
    },
    "id" | "profile_id_anime_id"
>;

export type AnimeFavoriteOrderByWithAggregationInput = {
    id?: Prisma.SortOrder;
    created_at?: Prisma.SortOrder;
    updated_at?: Prisma.SortOrder;
    profile_id?: Prisma.SortOrder;
    anime_id?: Prisma.SortOrder;
    vote?: Prisma.SortOrder;
    _count?: Prisma.AnimeFavoriteCountOrderByAggregateInput;
    _avg?: Prisma.AnimeFavoriteAvgOrderByAggregateInput;
    _max?: Prisma.AnimeFavoriteMaxOrderByAggregateInput;
    _min?: Prisma.AnimeFavoriteMinOrderByAggregateInput;
    _sum?: Prisma.AnimeFavoriteSumOrderByAggregateInput;
};

export type AnimeFavoriteScalarWhereWithAggregatesInput = {
    AND?: Prisma.AnimeFavoriteScalarWhereWithAggregatesInput | Prisma.AnimeFavoriteScalarWhereWithAggregatesInput[];
    OR?: Prisma.AnimeFavoriteScalarWhereWithAggregatesInput[];
    NOT?: Prisma.AnimeFavoriteScalarWhereWithAggregatesInput | Prisma.AnimeFavoriteScalarWhereWithAggregatesInput[];
    id?: Prisma.StringWithAggregatesFilter<"AnimeFavorite"> | string;
    created_at?: Prisma.DateTimeWithAggregatesFilter<"AnimeFavorite"> | Date | string;
    updated_at?: Prisma.DateTimeWithAggregatesFilter<"AnimeFavorite"> | Date | string;
    profile_id?: Prisma.StringWithAggregatesFilter<"AnimeFavorite"> | string;
    anime_id?: Prisma.IntWithAggregatesFilter<"AnimeFavorite"> | number;
    vote?: Prisma.BoolWithAggregatesFilter<"AnimeFavorite"> | boolean;
};

export type AnimeFavoriteCreateInput = {
    id?: string;
    created_at?: Date | string;
    updated_at?: Date | string;
    anime_id: number;
    vote: boolean;
    profile: Prisma.ProfileCreateNestedOneWithoutAnime_votesInput;
};

export type AnimeFavoriteUncheckedCreateInput = {
    id?: string;
    created_at?: Date | string;
    updated_at?: Date | string;
    profile_id: string;
    anime_id: number;
    vote: boolean;
};

export type AnimeFavoriteUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    anime_id?: Prisma.IntFieldUpdateOperationsInput | number;
    vote?: Prisma.BoolFieldUpdateOperationsInput | boolean;
    profile?: Prisma.ProfileUpdateOneRequiredWithoutAnime_votesNestedInput;
};

export type AnimeFavoriteUncheckedUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    profile_id?: Prisma.StringFieldUpdateOperationsInput | string;
    anime_id?: Prisma.IntFieldUpdateOperationsInput | number;
    vote?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type AnimeFavoriteCreateManyInput = {
    id?: string;
    created_at?: Date | string;
    updated_at?: Date | string;
    profile_id: string;
    anime_id: number;
    vote: boolean;
};

export type AnimeFavoriteUpdateManyMutationInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    anime_id?: Prisma.IntFieldUpdateOperationsInput | number;
    vote?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type AnimeFavoriteUncheckedUpdateManyInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    profile_id?: Prisma.StringFieldUpdateOperationsInput | string;
    anime_id?: Prisma.IntFieldUpdateOperationsInput | number;
    vote?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type AnimeFavoriteListRelationFilter = {
    every?: Prisma.AnimeFavoriteWhereInput;
    some?: Prisma.AnimeFavoriteWhereInput;
    none?: Prisma.AnimeFavoriteWhereInput;
};

export type AnimeFavoriteOrderByRelationAggregateInput = {
    _count?: Prisma.SortOrder;
};

export type AnimeFavoriteProfile_idAnime_idCompoundUniqueInput = {
    profile_id: string;
    anime_id: number;
};

export type AnimeFavoriteCountOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    created_at?: Prisma.SortOrder;
    updated_at?: Prisma.SortOrder;
    profile_id?: Prisma.SortOrder;
    anime_id?: Prisma.SortOrder;
    vote?: Prisma.SortOrder;
};

export type AnimeFavoriteAvgOrderByAggregateInput = {
    anime_id?: Prisma.SortOrder;
};

export type AnimeFavoriteMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    created_at?: Prisma.SortOrder;
    updated_at?: Prisma.SortOrder;
    profile_id?: Prisma.SortOrder;
    anime_id?: Prisma.SortOrder;
    vote?: Prisma.SortOrder;
};

export type AnimeFavoriteMinOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    created_at?: Prisma.SortOrder;
    updated_at?: Prisma.SortOrder;
    profile_id?: Prisma.SortOrder;
    anime_id?: Prisma.SortOrder;
    vote?: Prisma.SortOrder;
};

export type AnimeFavoriteSumOrderByAggregateInput = {
    anime_id?: Prisma.SortOrder;
};

export type AnimeFavoriteCreateNestedManyWithoutProfileInput = {
    create?:
        | Prisma.XOR<Prisma.AnimeFavoriteCreateWithoutProfileInput, Prisma.AnimeFavoriteUncheckedCreateWithoutProfileInput>
        | Prisma.AnimeFavoriteCreateWithoutProfileInput[]
        | Prisma.AnimeFavoriteUncheckedCreateWithoutProfileInput[];
    connectOrCreate?: Prisma.AnimeFavoriteCreateOrConnectWithoutProfileInput | Prisma.AnimeFavoriteCreateOrConnectWithoutProfileInput[];
    createMany?: Prisma.AnimeFavoriteCreateManyProfileInputEnvelope;
    connect?: Prisma.AnimeFavoriteWhereUniqueInput | Prisma.AnimeFavoriteWhereUniqueInput[];
};

export type AnimeFavoriteUncheckedCreateNestedManyWithoutProfileInput = {
    create?:
        | Prisma.XOR<Prisma.AnimeFavoriteCreateWithoutProfileInput, Prisma.AnimeFavoriteUncheckedCreateWithoutProfileInput>
        | Prisma.AnimeFavoriteCreateWithoutProfileInput[]
        | Prisma.AnimeFavoriteUncheckedCreateWithoutProfileInput[];
    connectOrCreate?: Prisma.AnimeFavoriteCreateOrConnectWithoutProfileInput | Prisma.AnimeFavoriteCreateOrConnectWithoutProfileInput[];
    createMany?: Prisma.AnimeFavoriteCreateManyProfileInputEnvelope;
    connect?: Prisma.AnimeFavoriteWhereUniqueInput | Prisma.AnimeFavoriteWhereUniqueInput[];
};

export type AnimeFavoriteUpdateManyWithoutProfileNestedInput = {
    create?:
        | Prisma.XOR<Prisma.AnimeFavoriteCreateWithoutProfileInput, Prisma.AnimeFavoriteUncheckedCreateWithoutProfileInput>
        | Prisma.AnimeFavoriteCreateWithoutProfileInput[]
        | Prisma.AnimeFavoriteUncheckedCreateWithoutProfileInput[];
    connectOrCreate?: Prisma.AnimeFavoriteCreateOrConnectWithoutProfileInput | Prisma.AnimeFavoriteCreateOrConnectWithoutProfileInput[];
    upsert?: Prisma.AnimeFavoriteUpsertWithWhereUniqueWithoutProfileInput | Prisma.AnimeFavoriteUpsertWithWhereUniqueWithoutProfileInput[];
    createMany?: Prisma.AnimeFavoriteCreateManyProfileInputEnvelope;
    set?: Prisma.AnimeFavoriteWhereUniqueInput | Prisma.AnimeFavoriteWhereUniqueInput[];
    disconnect?: Prisma.AnimeFavoriteWhereUniqueInput | Prisma.AnimeFavoriteWhereUniqueInput[];
    delete?: Prisma.AnimeFavoriteWhereUniqueInput | Prisma.AnimeFavoriteWhereUniqueInput[];
    connect?: Prisma.AnimeFavoriteWhereUniqueInput | Prisma.AnimeFavoriteWhereUniqueInput[];
    update?: Prisma.AnimeFavoriteUpdateWithWhereUniqueWithoutProfileInput | Prisma.AnimeFavoriteUpdateWithWhereUniqueWithoutProfileInput[];
    updateMany?: Prisma.AnimeFavoriteUpdateManyWithWhereWithoutProfileInput | Prisma.AnimeFavoriteUpdateManyWithWhereWithoutProfileInput[];
    deleteMany?: Prisma.AnimeFavoriteScalarWhereInput | Prisma.AnimeFavoriteScalarWhereInput[];
};

export type AnimeFavoriteUncheckedUpdateManyWithoutProfileNestedInput = {
    create?:
        | Prisma.XOR<Prisma.AnimeFavoriteCreateWithoutProfileInput, Prisma.AnimeFavoriteUncheckedCreateWithoutProfileInput>
        | Prisma.AnimeFavoriteCreateWithoutProfileInput[]
        | Prisma.AnimeFavoriteUncheckedCreateWithoutProfileInput[];
    connectOrCreate?: Prisma.AnimeFavoriteCreateOrConnectWithoutProfileInput | Prisma.AnimeFavoriteCreateOrConnectWithoutProfileInput[];
    upsert?: Prisma.AnimeFavoriteUpsertWithWhereUniqueWithoutProfileInput | Prisma.AnimeFavoriteUpsertWithWhereUniqueWithoutProfileInput[];
    createMany?: Prisma.AnimeFavoriteCreateManyProfileInputEnvelope;
    set?: Prisma.AnimeFavoriteWhereUniqueInput | Prisma.AnimeFavoriteWhereUniqueInput[];
    disconnect?: Prisma.AnimeFavoriteWhereUniqueInput | Prisma.AnimeFavoriteWhereUniqueInput[];
    delete?: Prisma.AnimeFavoriteWhereUniqueInput | Prisma.AnimeFavoriteWhereUniqueInput[];
    connect?: Prisma.AnimeFavoriteWhereUniqueInput | Prisma.AnimeFavoriteWhereUniqueInput[];
    update?: Prisma.AnimeFavoriteUpdateWithWhereUniqueWithoutProfileInput | Prisma.AnimeFavoriteUpdateWithWhereUniqueWithoutProfileInput[];
    updateMany?: Prisma.AnimeFavoriteUpdateManyWithWhereWithoutProfileInput | Prisma.AnimeFavoriteUpdateManyWithWhereWithoutProfileInput[];
    deleteMany?: Prisma.AnimeFavoriteScalarWhereInput | Prisma.AnimeFavoriteScalarWhereInput[];
};

export type AnimeFavoriteCreateWithoutProfileInput = {
    id?: string;
    created_at?: Date | string;
    updated_at?: Date | string;
    anime_id: number;
    vote: boolean;
};

export type AnimeFavoriteUncheckedCreateWithoutProfileInput = {
    id?: string;
    created_at?: Date | string;
    updated_at?: Date | string;
    anime_id: number;
    vote: boolean;
};

export type AnimeFavoriteCreateOrConnectWithoutProfileInput = {
    where: Prisma.AnimeFavoriteWhereUniqueInput;
    create: Prisma.XOR<Prisma.AnimeFavoriteCreateWithoutProfileInput, Prisma.AnimeFavoriteUncheckedCreateWithoutProfileInput>;
};

export type AnimeFavoriteCreateManyProfileInputEnvelope = {
    data: Prisma.AnimeFavoriteCreateManyProfileInput | Prisma.AnimeFavoriteCreateManyProfileInput[];
    skipDuplicates?: boolean;
};

export type AnimeFavoriteUpsertWithWhereUniqueWithoutProfileInput = {
    where: Prisma.AnimeFavoriteWhereUniqueInput;
    update: Prisma.XOR<Prisma.AnimeFavoriteUpdateWithoutProfileInput, Prisma.AnimeFavoriteUncheckedUpdateWithoutProfileInput>;
    create: Prisma.XOR<Prisma.AnimeFavoriteCreateWithoutProfileInput, Prisma.AnimeFavoriteUncheckedCreateWithoutProfileInput>;
};

export type AnimeFavoriteUpdateWithWhereUniqueWithoutProfileInput = {
    where: Prisma.AnimeFavoriteWhereUniqueInput;
    data: Prisma.XOR<Prisma.AnimeFavoriteUpdateWithoutProfileInput, Prisma.AnimeFavoriteUncheckedUpdateWithoutProfileInput>;
};

export type AnimeFavoriteUpdateManyWithWhereWithoutProfileInput = {
    where: Prisma.AnimeFavoriteScalarWhereInput;
    data: Prisma.XOR<Prisma.AnimeFavoriteUpdateManyMutationInput, Prisma.AnimeFavoriteUncheckedUpdateManyWithoutProfileInput>;
};

export type AnimeFavoriteScalarWhereInput = {
    AND?: Prisma.AnimeFavoriteScalarWhereInput | Prisma.AnimeFavoriteScalarWhereInput[];
    OR?: Prisma.AnimeFavoriteScalarWhereInput[];
    NOT?: Prisma.AnimeFavoriteScalarWhereInput | Prisma.AnimeFavoriteScalarWhereInput[];
    id?: Prisma.StringFilter<"AnimeFavorite"> | string;
    created_at?: Prisma.DateTimeFilter<"AnimeFavorite"> | Date | string;
    updated_at?: Prisma.DateTimeFilter<"AnimeFavorite"> | Date | string;
    profile_id?: Prisma.StringFilter<"AnimeFavorite"> | string;
    anime_id?: Prisma.IntFilter<"AnimeFavorite"> | number;
    vote?: Prisma.BoolFilter<"AnimeFavorite"> | boolean;
};

export type AnimeFavoriteCreateManyProfileInput = {
    id?: string;
    created_at?: Date | string;
    updated_at?: Date | string;
    anime_id: number;
    vote: boolean;
};

export type AnimeFavoriteUpdateWithoutProfileInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    anime_id?: Prisma.IntFieldUpdateOperationsInput | number;
    vote?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type AnimeFavoriteUncheckedUpdateWithoutProfileInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    anime_id?: Prisma.IntFieldUpdateOperationsInput | number;
    vote?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type AnimeFavoriteUncheckedUpdateManyWithoutProfileInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    anime_id?: Prisma.IntFieldUpdateOperationsInput | number;
    vote?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type AnimeFavoriteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
    runtime.Types.Extensions.GetSelect<
        {
            id?: boolean;
            created_at?: boolean;
            updated_at?: boolean;
            profile_id?: boolean;
            anime_id?: boolean;
            vote?: boolean;
            profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
        },
        ExtArgs["result"]["animeFavorite"]
    >;

export type AnimeFavoriteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
    runtime.Types.Extensions.GetSelect<
        {
            id?: boolean;
            created_at?: boolean;
            updated_at?: boolean;
            profile_id?: boolean;
            anime_id?: boolean;
            vote?: boolean;
            profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
        },
        ExtArgs["result"]["animeFavorite"]
    >;

export type AnimeFavoriteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
    runtime.Types.Extensions.GetSelect<
        {
            id?: boolean;
            created_at?: boolean;
            updated_at?: boolean;
            profile_id?: boolean;
            anime_id?: boolean;
            vote?: boolean;
            profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
        },
        ExtArgs["result"]["animeFavorite"]
    >;

export type AnimeFavoriteSelectScalar = {
    id?: boolean;
    created_at?: boolean;
    updated_at?: boolean;
    profile_id?: boolean;
    anime_id?: boolean;
    vote?: boolean;
};

export type AnimeFavoriteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
    runtime.Types.Extensions.GetOmit<"id" | "created_at" | "updated_at" | "profile_id" | "anime_id" | "vote", ExtArgs["result"]["animeFavorite"]>;
export type AnimeFavoriteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
};
export type AnimeFavoriteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
};
export type AnimeFavoriteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
};

export type $AnimeFavoritePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    name: "AnimeFavorite";
    objects: {
        profile: Prisma.$ProfilePayload<ExtArgs>;
    };
    scalars: runtime.Types.Extensions.GetPayloadResult<
        {
            id: string;
            created_at: Date;
            updated_at: Date;
            profile_id: string;
            anime_id: number;
            vote: boolean;
        },
        ExtArgs["result"]["animeFavorite"]
    >;
    composites: {};
};

export type AnimeFavoriteGetPayload<S extends boolean | null | undefined | AnimeFavoriteDefaultArgs> = runtime.Types.Result.GetResult<
    Prisma.$AnimeFavoritePayload,
    S
>;

export type AnimeFavoriteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = Omit<
    AnimeFavoriteFindManyArgs,
    "select" | "include" | "distinct" | "omit"
> & {
    select?: AnimeFavoriteCountAggregateInputType | true;
};

export interface AnimeFavoriteDelegate<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> {
    [K: symbol]: { types: Prisma.TypeMap<ExtArgs>["model"]["AnimeFavorite"]; meta: { name: "AnimeFavorite" } };
    /**
     * Find zero or one AnimeFavorite that matches the filter.
     * @param {AnimeFavoriteFindUniqueArgs} args - Arguments to find a AnimeFavorite
     * @example
     * // Get one AnimeFavorite
     * const animeFavorite = await prisma.animeFavorite.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends AnimeFavoriteFindUniqueArgs>(
        args: Prisma.SelectSubset<T, AnimeFavoriteFindUniqueArgs<ExtArgs>>,
    ): Prisma.Prisma__AnimeFavoriteClient<
        runtime.Types.Result.GetResult<Prisma.$AnimeFavoritePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find one AnimeFavorite that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {AnimeFavoriteFindUniqueOrThrowArgs} args - Arguments to find a AnimeFavorite
     * @example
     * // Get one AnimeFavorite
     * const animeFavorite = await prisma.animeFavorite.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends AnimeFavoriteFindUniqueOrThrowArgs>(
        args: Prisma.SelectSubset<T, AnimeFavoriteFindUniqueOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__AnimeFavoriteClient<
        runtime.Types.Result.GetResult<Prisma.$AnimeFavoritePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first AnimeFavorite that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AnimeFavoriteFindFirstArgs} args - Arguments to find a AnimeFavorite
     * @example
     * // Get one AnimeFavorite
     * const animeFavorite = await prisma.animeFavorite.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends AnimeFavoriteFindFirstArgs>(
        args?: Prisma.SelectSubset<T, AnimeFavoriteFindFirstArgs<ExtArgs>>,
    ): Prisma.Prisma__AnimeFavoriteClient<
        runtime.Types.Result.GetResult<Prisma.$AnimeFavoritePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first AnimeFavorite that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AnimeFavoriteFindFirstOrThrowArgs} args - Arguments to find a AnimeFavorite
     * @example
     * // Get one AnimeFavorite
     * const animeFavorite = await prisma.animeFavorite.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends AnimeFavoriteFindFirstOrThrowArgs>(
        args?: Prisma.SelectSubset<T, AnimeFavoriteFindFirstOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__AnimeFavoriteClient<
        runtime.Types.Result.GetResult<Prisma.$AnimeFavoritePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find zero or more AnimeFavorites that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AnimeFavoriteFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all AnimeFavorites
     * const animeFavorites = await prisma.animeFavorite.findMany()
     *
     * // Get first 10 AnimeFavorites
     * const animeFavorites = await prisma.animeFavorite.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const animeFavoriteWithIdOnly = await prisma.animeFavorite.findMany({ select: { id: true } })
     *
     */
    findMany<T extends AnimeFavoriteFindManyArgs>(
        args?: Prisma.SelectSubset<T, AnimeFavoriteFindManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnimeFavoritePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>;

    /**
     * Create a AnimeFavorite.
     * @param {AnimeFavoriteCreateArgs} args - Arguments to create a AnimeFavorite.
     * @example
     * // Create one AnimeFavorite
     * const AnimeFavorite = await prisma.animeFavorite.create({
     *   data: {
     *     // ... data to create a AnimeFavorite
     *   }
     * })
     *
     */
    create<T extends AnimeFavoriteCreateArgs>(
        args: Prisma.SelectSubset<T, AnimeFavoriteCreateArgs<ExtArgs>>,
    ): Prisma.Prisma__AnimeFavoriteClient<
        runtime.Types.Result.GetResult<Prisma.$AnimeFavoritePayload<ExtArgs>, T, "create", GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Create many AnimeFavorites.
     * @param {AnimeFavoriteCreateManyArgs} args - Arguments to create many AnimeFavorites.
     * @example
     * // Create many AnimeFavorites
     * const animeFavorite = await prisma.animeFavorite.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends AnimeFavoriteCreateManyArgs>(
        args?: Prisma.SelectSubset<T, AnimeFavoriteCreateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Create many AnimeFavorites and returns the data saved in the database.
     * @param {AnimeFavoriteCreateManyAndReturnArgs} args - Arguments to create many AnimeFavorites.
     * @example
     * // Create many AnimeFavorites
     * const animeFavorite = await prisma.animeFavorite.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many AnimeFavorites and only return the `id`
     * const animeFavoriteWithIdOnly = await prisma.animeFavorite.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends AnimeFavoriteCreateManyAndReturnArgs>(
        args?: Prisma.SelectSubset<T, AnimeFavoriteCreateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnimeFavoritePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>;

    /**
     * Delete a AnimeFavorite.
     * @param {AnimeFavoriteDeleteArgs} args - Arguments to delete one AnimeFavorite.
     * @example
     * // Delete one AnimeFavorite
     * const AnimeFavorite = await prisma.animeFavorite.delete({
     *   where: {
     *     // ... filter to delete one AnimeFavorite
     *   }
     * })
     *
     */
    delete<T extends AnimeFavoriteDeleteArgs>(
        args: Prisma.SelectSubset<T, AnimeFavoriteDeleteArgs<ExtArgs>>,
    ): Prisma.Prisma__AnimeFavoriteClient<
        runtime.Types.Result.GetResult<Prisma.$AnimeFavoritePayload<ExtArgs>, T, "delete", GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Update one AnimeFavorite.
     * @param {AnimeFavoriteUpdateArgs} args - Arguments to update one AnimeFavorite.
     * @example
     * // Update one AnimeFavorite
     * const animeFavorite = await prisma.animeFavorite.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends AnimeFavoriteUpdateArgs>(
        args: Prisma.SelectSubset<T, AnimeFavoriteUpdateArgs<ExtArgs>>,
    ): Prisma.Prisma__AnimeFavoriteClient<
        runtime.Types.Result.GetResult<Prisma.$AnimeFavoritePayload<ExtArgs>, T, "update", GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Delete zero or more AnimeFavorites.
     * @param {AnimeFavoriteDeleteManyArgs} args - Arguments to filter AnimeFavorites to delete.
     * @example
     * // Delete a few AnimeFavorites
     * const { count } = await prisma.animeFavorite.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends AnimeFavoriteDeleteManyArgs>(
        args?: Prisma.SelectSubset<T, AnimeFavoriteDeleteManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more AnimeFavorites.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AnimeFavoriteUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many AnimeFavorites
     * const animeFavorite = await prisma.animeFavorite.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends AnimeFavoriteUpdateManyArgs>(
        args: Prisma.SelectSubset<T, AnimeFavoriteUpdateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more AnimeFavorites and returns the data updated in the database.
     * @param {AnimeFavoriteUpdateManyAndReturnArgs} args - Arguments to update many AnimeFavorites.
     * @example
     * // Update many AnimeFavorites
     * const animeFavorite = await prisma.animeFavorite.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more AnimeFavorites and only return the `id`
     * const animeFavoriteWithIdOnly = await prisma.animeFavorite.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends AnimeFavoriteUpdateManyAndReturnArgs>(
        args: Prisma.SelectSubset<T, AnimeFavoriteUpdateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnimeFavoritePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>;

    /**
     * Create or update one AnimeFavorite.
     * @param {AnimeFavoriteUpsertArgs} args - Arguments to update or create a AnimeFavorite.
     * @example
     * // Update or create a AnimeFavorite
     * const animeFavorite = await prisma.animeFavorite.upsert({
     *   create: {
     *     // ... data to create a AnimeFavorite
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the AnimeFavorite we want to update
     *   }
     * })
     */
    upsert<T extends AnimeFavoriteUpsertArgs>(
        args: Prisma.SelectSubset<T, AnimeFavoriteUpsertArgs<ExtArgs>>,
    ): Prisma.Prisma__AnimeFavoriteClient<
        runtime.Types.Result.GetResult<Prisma.$AnimeFavoritePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Count the number of AnimeFavorites.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AnimeFavoriteCountArgs} args - Arguments to filter AnimeFavorites to count.
     * @example
     * // Count the number of AnimeFavorites
     * const count = await prisma.animeFavorite.count({
     *   where: {
     *     // ... the filter for the AnimeFavorites we want to count
     *   }
     * })
     **/
    count<T extends AnimeFavoriteCountArgs>(
        args?: Prisma.Subset<T, AnimeFavoriteCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<"select", any>
            ? T["select"] extends true
                ? number
                : Prisma.GetScalarType<T["select"], AnimeFavoriteCountAggregateOutputType>
            : number
    >;

    /**
     * Allows you to perform aggregations operations on a AnimeFavorite.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AnimeFavoriteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends AnimeFavoriteAggregateArgs>(
        args: Prisma.Subset<T, AnimeFavoriteAggregateArgs>,
    ): Prisma.PrismaPromise<GetAnimeFavoriteAggregateType<T>>;

    /**
     * Group by AnimeFavorite.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AnimeFavoriteGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends AnimeFavoriteGroupByArgs,
        HasSelectOrTake extends Prisma.Or<Prisma.Extends<"skip", Prisma.Keys<T>>, Prisma.Extends<"take", Prisma.Keys<T>>>,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: AnimeFavoriteGroupByArgs["orderBy"] }
            : { orderBy?: AnimeFavoriteGroupByArgs["orderBy"] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>>,
        ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T["having"]>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
            ? {
                  [P in HavingFields]: P extends ByFields
                      ? never
                      : P extends string
                      ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                      : [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
              }[HavingFields]
            : "take" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
                ? ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields]
                : 'Error: If you provide "take", you also need to provide "orderBy"'
            : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
                ? ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields]
                : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
            ? {}
            : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
    >(
        args: Prisma.SubsetIntersection<T, AnimeFavoriteGroupByArgs, OrderByArg> & InputErrors,
    ): {} extends InputErrors ? GetAnimeFavoriteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
    /**
     * Fields of the AnimeFavorite model
     */
    readonly fields: AnimeFavoriteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AnimeFavorite.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AnimeFavoriteClient<
    T,
    Null = never,
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: "PrismaPromise";
    profile<T extends Prisma.ProfileDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.ProfileDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__ProfileClient<
        runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(
        onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
        onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
    ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(
        onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
    ): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the AnimeFavorite model
 */
export interface AnimeFavoriteFieldRefs {
    readonly id: Prisma.FieldRef<"AnimeFavorite", "String">;
    readonly created_at: Prisma.FieldRef<"AnimeFavorite", "DateTime">;
    readonly updated_at: Prisma.FieldRef<"AnimeFavorite", "DateTime">;
    readonly profile_id: Prisma.FieldRef<"AnimeFavorite", "String">;
    readonly anime_id: Prisma.FieldRef<"AnimeFavorite", "Int">;
    readonly vote: Prisma.FieldRef<"AnimeFavorite", "Boolean">;
}

// Custom InputTypes
/**
 * AnimeFavorite findUnique
 */
export type AnimeFavoriteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the AnimeFavorite
     */
    select?: Prisma.AnimeFavoriteSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AnimeFavorite
     */
    omit?: Prisma.AnimeFavoriteOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AnimeFavoriteInclude<ExtArgs> | null;
    /**
     * Filter, which AnimeFavorite to fetch.
     */
    where: Prisma.AnimeFavoriteWhereUniqueInput;
};

/**
 * AnimeFavorite findUniqueOrThrow
 */
export type AnimeFavoriteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the AnimeFavorite
     */
    select?: Prisma.AnimeFavoriteSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AnimeFavorite
     */
    omit?: Prisma.AnimeFavoriteOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AnimeFavoriteInclude<ExtArgs> | null;
    /**
     * Filter, which AnimeFavorite to fetch.
     */
    where: Prisma.AnimeFavoriteWhereUniqueInput;
};

/**
 * AnimeFavorite findFirst
 */
export type AnimeFavoriteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the AnimeFavorite
     */
    select?: Prisma.AnimeFavoriteSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AnimeFavorite
     */
    omit?: Prisma.AnimeFavoriteOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AnimeFavoriteInclude<ExtArgs> | null;
    /**
     * Filter, which AnimeFavorite to fetch.
     */
    where?: Prisma.AnimeFavoriteWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of AnimeFavorites to fetch.
     */
    orderBy?: Prisma.AnimeFavoriteOrderByWithRelationInput | Prisma.AnimeFavoriteOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for AnimeFavorites.
     */
    cursor?: Prisma.AnimeFavoriteWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` AnimeFavorites from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` AnimeFavorites.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of AnimeFavorites.
     */
    distinct?: Prisma.AnimeFavoriteScalarFieldEnum | Prisma.AnimeFavoriteScalarFieldEnum[];
};

/**
 * AnimeFavorite findFirstOrThrow
 */
export type AnimeFavoriteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the AnimeFavorite
     */
    select?: Prisma.AnimeFavoriteSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AnimeFavorite
     */
    omit?: Prisma.AnimeFavoriteOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AnimeFavoriteInclude<ExtArgs> | null;
    /**
     * Filter, which AnimeFavorite to fetch.
     */
    where?: Prisma.AnimeFavoriteWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of AnimeFavorites to fetch.
     */
    orderBy?: Prisma.AnimeFavoriteOrderByWithRelationInput | Prisma.AnimeFavoriteOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for AnimeFavorites.
     */
    cursor?: Prisma.AnimeFavoriteWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` AnimeFavorites from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` AnimeFavorites.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of AnimeFavorites.
     */
    distinct?: Prisma.AnimeFavoriteScalarFieldEnum | Prisma.AnimeFavoriteScalarFieldEnum[];
};

/**
 * AnimeFavorite findMany
 */
export type AnimeFavoriteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the AnimeFavorite
     */
    select?: Prisma.AnimeFavoriteSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AnimeFavorite
     */
    omit?: Prisma.AnimeFavoriteOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AnimeFavoriteInclude<ExtArgs> | null;
    /**
     * Filter, which AnimeFavorites to fetch.
     */
    where?: Prisma.AnimeFavoriteWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of AnimeFavorites to fetch.
     */
    orderBy?: Prisma.AnimeFavoriteOrderByWithRelationInput | Prisma.AnimeFavoriteOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing AnimeFavorites.
     */
    cursor?: Prisma.AnimeFavoriteWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` AnimeFavorites from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` AnimeFavorites.
     */
    skip?: number;
    distinct?: Prisma.AnimeFavoriteScalarFieldEnum | Prisma.AnimeFavoriteScalarFieldEnum[];
};

/**
 * AnimeFavorite create
 */
export type AnimeFavoriteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the AnimeFavorite
     */
    select?: Prisma.AnimeFavoriteSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AnimeFavorite
     */
    omit?: Prisma.AnimeFavoriteOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AnimeFavoriteInclude<ExtArgs> | null;
    /**
     * The data needed to create a AnimeFavorite.
     */
    data: Prisma.XOR<Prisma.AnimeFavoriteCreateInput, Prisma.AnimeFavoriteUncheckedCreateInput>;
};

/**
 * AnimeFavorite createMany
 */
export type AnimeFavoriteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * The data used to create many AnimeFavorites.
     */
    data: Prisma.AnimeFavoriteCreateManyInput | Prisma.AnimeFavoriteCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * AnimeFavorite createManyAndReturn
 */
export type AnimeFavoriteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the AnimeFavorite
     */
    select?: Prisma.AnimeFavoriteSelectCreateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the AnimeFavorite
     */
    omit?: Prisma.AnimeFavoriteOmit<ExtArgs> | null;
    /**
     * The data used to create many AnimeFavorites.
     */
    data: Prisma.AnimeFavoriteCreateManyInput | Prisma.AnimeFavoriteCreateManyInput[];
    skipDuplicates?: boolean;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AnimeFavoriteIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * AnimeFavorite update
 */
export type AnimeFavoriteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the AnimeFavorite
     */
    select?: Prisma.AnimeFavoriteSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AnimeFavorite
     */
    omit?: Prisma.AnimeFavoriteOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AnimeFavoriteInclude<ExtArgs> | null;
    /**
     * The data needed to update a AnimeFavorite.
     */
    data: Prisma.XOR<Prisma.AnimeFavoriteUpdateInput, Prisma.AnimeFavoriteUncheckedUpdateInput>;
    /**
     * Choose, which AnimeFavorite to update.
     */
    where: Prisma.AnimeFavoriteWhereUniqueInput;
};

/**
 * AnimeFavorite updateMany
 */
export type AnimeFavoriteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * The data used to update AnimeFavorites.
     */
    data: Prisma.XOR<Prisma.AnimeFavoriteUpdateManyMutationInput, Prisma.AnimeFavoriteUncheckedUpdateManyInput>;
    /**
     * Filter which AnimeFavorites to update
     */
    where?: Prisma.AnimeFavoriteWhereInput;
    /**
     * Limit how many AnimeFavorites to update.
     */
    limit?: number;
};

/**
 * AnimeFavorite updateManyAndReturn
 */
export type AnimeFavoriteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the AnimeFavorite
     */
    select?: Prisma.AnimeFavoriteSelectUpdateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the AnimeFavorite
     */
    omit?: Prisma.AnimeFavoriteOmit<ExtArgs> | null;
    /**
     * The data used to update AnimeFavorites.
     */
    data: Prisma.XOR<Prisma.AnimeFavoriteUpdateManyMutationInput, Prisma.AnimeFavoriteUncheckedUpdateManyInput>;
    /**
     * Filter which AnimeFavorites to update
     */
    where?: Prisma.AnimeFavoriteWhereInput;
    /**
     * Limit how many AnimeFavorites to update.
     */
    limit?: number;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AnimeFavoriteIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * AnimeFavorite upsert
 */
export type AnimeFavoriteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the AnimeFavorite
     */
    select?: Prisma.AnimeFavoriteSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AnimeFavorite
     */
    omit?: Prisma.AnimeFavoriteOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AnimeFavoriteInclude<ExtArgs> | null;
    /**
     * The filter to search for the AnimeFavorite to update in case it exists.
     */
    where: Prisma.AnimeFavoriteWhereUniqueInput;
    /**
     * In case the AnimeFavorite found by the `where` argument doesn't exist, create a new AnimeFavorite with this data.
     */
    create: Prisma.XOR<Prisma.AnimeFavoriteCreateInput, Prisma.AnimeFavoriteUncheckedCreateInput>;
    /**
     * In case the AnimeFavorite was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<Prisma.AnimeFavoriteUpdateInput, Prisma.AnimeFavoriteUncheckedUpdateInput>;
};

/**
 * AnimeFavorite delete
 */
export type AnimeFavoriteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the AnimeFavorite
     */
    select?: Prisma.AnimeFavoriteSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AnimeFavorite
     */
    omit?: Prisma.AnimeFavoriteOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AnimeFavoriteInclude<ExtArgs> | null;
    /**
     * Filter which AnimeFavorite to delete.
     */
    where: Prisma.AnimeFavoriteWhereUniqueInput;
};

/**
 * AnimeFavorite deleteMany
 */
export type AnimeFavoriteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Filter which AnimeFavorites to delete
     */
    where?: Prisma.AnimeFavoriteWhereInput;
    /**
     * Limit how many AnimeFavorites to delete.
     */
    limit?: number;
};

/**
 * AnimeFavorite without action
 */
export type AnimeFavoriteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the AnimeFavorite
     */
    select?: Prisma.AnimeFavoriteSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AnimeFavorite
     */
    omit?: Prisma.AnimeFavoriteOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AnimeFavoriteInclude<ExtArgs> | null;
};

