
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `AvatarPicture` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AvatarPicture
 * 
 */
export type AvatarPictureModel = runtime.Types.Result.DefaultSelection<Prisma.$AvatarPicturePayload>

export type AggregateAvatarPicture = {
  _count: AvatarPictureCountAggregateOutputType | null
  _min: AvatarPictureMinAggregateOutputType | null
  _max: AvatarPictureMaxAggregateOutputType | null
}

export type AvatarPictureMinAggregateOutputType = {
  id: string | null
  created_at: Date | null
  updated_at: Date | null
  url: string | null
  by_profile_id: string | null
}

export type AvatarPictureMaxAggregateOutputType = {
  id: string | null
  created_at: Date | null
  updated_at: Date | null
  url: string | null
  by_profile_id: string | null
}

export type AvatarPictureCountAggregateOutputType = {
  id: number
  created_at: number
  updated_at: number
  url: number
  by_profile_id: number
  _all: number
}


export type AvatarPictureMinAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  url?: true
  by_profile_id?: true
}

export type AvatarPictureMaxAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  url?: true
  by_profile_id?: true
}

export type AvatarPictureCountAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  url?: true
  by_profile_id?: true
  _all?: true
}

export type AvatarPictureAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AvatarPicture to aggregate.
   */
  where?: Prisma.AvatarPictureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AvatarPictures to fetch.
   */
  orderBy?: Prisma.AvatarPictureOrderByWithRelationInput | Prisma.AvatarPictureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AvatarPictureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AvatarPictures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AvatarPictures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AvatarPictures
  **/
  _count?: true | AvatarPictureCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AvatarPictureMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AvatarPictureMaxAggregateInputType
}

export type GetAvatarPictureAggregateType<T extends AvatarPictureAggregateArgs> = {
      [P in keyof T & keyof AggregateAvatarPicture]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAvatarPicture[P]>
    : Prisma.GetScalarType<T[P], AggregateAvatarPicture[P]>
}




export type AvatarPictureGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AvatarPictureWhereInput
  orderBy?: Prisma.AvatarPictureOrderByWithAggregationInput | Prisma.AvatarPictureOrderByWithAggregationInput[]
  by: Prisma.AvatarPictureScalarFieldEnum[] | Prisma.AvatarPictureScalarFieldEnum
  having?: Prisma.AvatarPictureScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AvatarPictureCountAggregateInputType | true
  _min?: AvatarPictureMinAggregateInputType
  _max?: AvatarPictureMaxAggregateInputType
}

export type AvatarPictureGroupByOutputType = {
  id: string
  created_at: Date
  updated_at: Date
  url: string
  by_profile_id: string
  _count: AvatarPictureCountAggregateOutputType | null
  _min: AvatarPictureMinAggregateOutputType | null
  _max: AvatarPictureMaxAggregateOutputType | null
}

type GetAvatarPictureGroupByPayload<T extends AvatarPictureGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AvatarPictureGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AvatarPictureGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AvatarPictureGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AvatarPictureGroupByOutputType[P]>
      }
    >
  >



export type AvatarPictureWhereInput = {
  AND?: Prisma.AvatarPictureWhereInput | Prisma.AvatarPictureWhereInput[]
  OR?: Prisma.AvatarPictureWhereInput[]
  NOT?: Prisma.AvatarPictureWhereInput | Prisma.AvatarPictureWhereInput[]
  id?: Prisma.StringFilter<"AvatarPicture"> | string
  created_at?: Prisma.DateTimeFilter<"AvatarPicture"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"AvatarPicture"> | Date | string
  url?: Prisma.StringFilter<"AvatarPicture"> | string
  by_profile_id?: Prisma.StringFilter<"AvatarPicture"> | string
  by_profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
}

export type AvatarPictureOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  url?: Prisma.SortOrder
  by_profile_id?: Prisma.SortOrder
  by_profile?: Prisma.ProfileOrderByWithRelationInput
}

export type AvatarPictureWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  by_profile_id?: string
  AND?: Prisma.AvatarPictureWhereInput | Prisma.AvatarPictureWhereInput[]
  OR?: Prisma.AvatarPictureWhereInput[]
  NOT?: Prisma.AvatarPictureWhereInput | Prisma.AvatarPictureWhereInput[]
  created_at?: Prisma.DateTimeFilter<"AvatarPicture"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"AvatarPicture"> | Date | string
  url?: Prisma.StringFilter<"AvatarPicture"> | string
  by_profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
}, "id" | "by_profile_id">

export type AvatarPictureOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  url?: Prisma.SortOrder
  by_profile_id?: Prisma.SortOrder
  _count?: Prisma.AvatarPictureCountOrderByAggregateInput
  _max?: Prisma.AvatarPictureMaxOrderByAggregateInput
  _min?: Prisma.AvatarPictureMinOrderByAggregateInput
}

export type AvatarPictureScalarWhereWithAggregatesInput = {
  AND?: Prisma.AvatarPictureScalarWhereWithAggregatesInput | Prisma.AvatarPictureScalarWhereWithAggregatesInput[]
  OR?: Prisma.AvatarPictureScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AvatarPictureScalarWhereWithAggregatesInput | Prisma.AvatarPictureScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AvatarPicture"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"AvatarPicture"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"AvatarPicture"> | Date | string
  url?: Prisma.StringWithAggregatesFilter<"AvatarPicture"> | string
  by_profile_id?: Prisma.StringWithAggregatesFilter<"AvatarPicture"> | string
}

export type AvatarPictureCreateInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  url: string
  by_profile: Prisma.ProfileCreateNestedOneWithoutAvatarInput
}

export type AvatarPictureUncheckedCreateInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  url: string
  by_profile_id: string
}

export type AvatarPictureUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  by_profile?: Prisma.ProfileUpdateOneRequiredWithoutAvatarNestedInput
}

export type AvatarPictureUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  by_profile_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AvatarPictureCreateManyInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  url: string
  by_profile_id: string
}

export type AvatarPictureUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AvatarPictureUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  by_profile_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AvatarPictureCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  url?: Prisma.SortOrder
  by_profile_id?: Prisma.SortOrder
}

export type AvatarPictureMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  url?: Prisma.SortOrder
  by_profile_id?: Prisma.SortOrder
}

export type AvatarPictureMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  url?: Prisma.SortOrder
  by_profile_id?: Prisma.SortOrder
}

export type AvatarPictureNullableScalarRelationFilter = {
  is?: Prisma.AvatarPictureWhereInput | null
  isNot?: Prisma.AvatarPictureWhereInput | null
}

export type AvatarPictureCreateNestedOneWithoutBy_profileInput = {
  create?: Prisma.XOR<Prisma.AvatarPictureCreateWithoutBy_profileInput, Prisma.AvatarPictureUncheckedCreateWithoutBy_profileInput>
  connectOrCreate?: Prisma.AvatarPictureCreateOrConnectWithoutBy_profileInput
  connect?: Prisma.AvatarPictureWhereUniqueInput
}

export type AvatarPictureUncheckedCreateNestedOneWithoutBy_profileInput = {
  create?: Prisma.XOR<Prisma.AvatarPictureCreateWithoutBy_profileInput, Prisma.AvatarPictureUncheckedCreateWithoutBy_profileInput>
  connectOrCreate?: Prisma.AvatarPictureCreateOrConnectWithoutBy_profileInput
  connect?: Prisma.AvatarPictureWhereUniqueInput
}

export type AvatarPictureUpdateOneWithoutBy_profileNestedInput = {
  create?: Prisma.XOR<Prisma.AvatarPictureCreateWithoutBy_profileInput, Prisma.AvatarPictureUncheckedCreateWithoutBy_profileInput>
  connectOrCreate?: Prisma.AvatarPictureCreateOrConnectWithoutBy_profileInput
  upsert?: Prisma.AvatarPictureUpsertWithoutBy_profileInput
  disconnect?: Prisma.AvatarPictureWhereInput | boolean
  delete?: Prisma.AvatarPictureWhereInput | boolean
  connect?: Prisma.AvatarPictureWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AvatarPictureUpdateToOneWithWhereWithoutBy_profileInput, Prisma.AvatarPictureUpdateWithoutBy_profileInput>, Prisma.AvatarPictureUncheckedUpdateWithoutBy_profileInput>
}

export type AvatarPictureUncheckedUpdateOneWithoutBy_profileNestedInput = {
  create?: Prisma.XOR<Prisma.AvatarPictureCreateWithoutBy_profileInput, Prisma.AvatarPictureUncheckedCreateWithoutBy_profileInput>
  connectOrCreate?: Prisma.AvatarPictureCreateOrConnectWithoutBy_profileInput
  upsert?: Prisma.AvatarPictureUpsertWithoutBy_profileInput
  disconnect?: Prisma.AvatarPictureWhereInput | boolean
  delete?: Prisma.AvatarPictureWhereInput | boolean
  connect?: Prisma.AvatarPictureWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AvatarPictureUpdateToOneWithWhereWithoutBy_profileInput, Prisma.AvatarPictureUpdateWithoutBy_profileInput>, Prisma.AvatarPictureUncheckedUpdateWithoutBy_profileInput>
}

export type AvatarPictureCreateWithoutBy_profileInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  url: string
}

export type AvatarPictureUncheckedCreateWithoutBy_profileInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  url: string
}

export type AvatarPictureCreateOrConnectWithoutBy_profileInput = {
  where: Prisma.AvatarPictureWhereUniqueInput
  create: Prisma.XOR<Prisma.AvatarPictureCreateWithoutBy_profileInput, Prisma.AvatarPictureUncheckedCreateWithoutBy_profileInput>
}

export type AvatarPictureUpsertWithoutBy_profileInput = {
  update: Prisma.XOR<Prisma.AvatarPictureUpdateWithoutBy_profileInput, Prisma.AvatarPictureUncheckedUpdateWithoutBy_profileInput>
  create: Prisma.XOR<Prisma.AvatarPictureCreateWithoutBy_profileInput, Prisma.AvatarPictureUncheckedCreateWithoutBy_profileInput>
  where?: Prisma.AvatarPictureWhereInput
}

export type AvatarPictureUpdateToOneWithWhereWithoutBy_profileInput = {
  where?: Prisma.AvatarPictureWhereInput
  data: Prisma.XOR<Prisma.AvatarPictureUpdateWithoutBy_profileInput, Prisma.AvatarPictureUncheckedUpdateWithoutBy_profileInput>
}

export type AvatarPictureUpdateWithoutBy_profileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AvatarPictureUncheckedUpdateWithoutBy_profileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}



export type AvatarPictureSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  url?: boolean
  by_profile_id?: boolean
  by_profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["avatarPicture"]>

export type AvatarPictureSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  url?: boolean
  by_profile_id?: boolean
  by_profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["avatarPicture"]>

export type AvatarPictureSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  url?: boolean
  by_profile_id?: boolean
  by_profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["avatarPicture"]>

export type AvatarPictureSelectScalar = {
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  url?: boolean
  by_profile_id?: boolean
}

export type AvatarPictureOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "created_at" | "updated_at" | "url" | "by_profile_id", ExtArgs["result"]["avatarPicture"]>
export type AvatarPictureInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  by_profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}
export type AvatarPictureIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  by_profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}
export type AvatarPictureIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  by_profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}

export type $AvatarPicturePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AvatarPicture"
  objects: {
    by_profile: Prisma.$ProfilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    created_at: Date
    updated_at: Date
    url: string
    by_profile_id: string
  }, ExtArgs["result"]["avatarPicture"]>
  composites: {}
}

export type AvatarPictureGetPayload<S extends boolean | null | undefined | AvatarPictureDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AvatarPicturePayload, S>

export type AvatarPictureCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AvatarPictureFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AvatarPictureCountAggregateInputType | true
  }

export interface AvatarPictureDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AvatarPicture'], meta: { name: 'AvatarPicture' } }
  /**
   * Find zero or one AvatarPicture that matches the filter.
   * @param {AvatarPictureFindUniqueArgs} args - Arguments to find a AvatarPicture
   * @example
   * // Get one AvatarPicture
   * const avatarPicture = await prisma.avatarPicture.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AvatarPictureFindUniqueArgs>(args: Prisma.SelectSubset<T, AvatarPictureFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AvatarPictureClient<runtime.Types.Result.GetResult<Prisma.$AvatarPicturePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AvatarPicture that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AvatarPictureFindUniqueOrThrowArgs} args - Arguments to find a AvatarPicture
   * @example
   * // Get one AvatarPicture
   * const avatarPicture = await prisma.avatarPicture.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AvatarPictureFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AvatarPictureFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AvatarPictureClient<runtime.Types.Result.GetResult<Prisma.$AvatarPicturePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AvatarPicture that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvatarPictureFindFirstArgs} args - Arguments to find a AvatarPicture
   * @example
   * // Get one AvatarPicture
   * const avatarPicture = await prisma.avatarPicture.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AvatarPictureFindFirstArgs>(args?: Prisma.SelectSubset<T, AvatarPictureFindFirstArgs<ExtArgs>>): Prisma.Prisma__AvatarPictureClient<runtime.Types.Result.GetResult<Prisma.$AvatarPicturePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AvatarPicture that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvatarPictureFindFirstOrThrowArgs} args - Arguments to find a AvatarPicture
   * @example
   * // Get one AvatarPicture
   * const avatarPicture = await prisma.avatarPicture.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AvatarPictureFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AvatarPictureFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AvatarPictureClient<runtime.Types.Result.GetResult<Prisma.$AvatarPicturePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AvatarPictures that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvatarPictureFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AvatarPictures
   * const avatarPictures = await prisma.avatarPicture.findMany()
   * 
   * // Get first 10 AvatarPictures
   * const avatarPictures = await prisma.avatarPicture.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const avatarPictureWithIdOnly = await prisma.avatarPicture.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AvatarPictureFindManyArgs>(args?: Prisma.SelectSubset<T, AvatarPictureFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AvatarPicturePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AvatarPicture.
   * @param {AvatarPictureCreateArgs} args - Arguments to create a AvatarPicture.
   * @example
   * // Create one AvatarPicture
   * const AvatarPicture = await prisma.avatarPicture.create({
   *   data: {
   *     // ... data to create a AvatarPicture
   *   }
   * })
   * 
   */
  create<T extends AvatarPictureCreateArgs>(args: Prisma.SelectSubset<T, AvatarPictureCreateArgs<ExtArgs>>): Prisma.Prisma__AvatarPictureClient<runtime.Types.Result.GetResult<Prisma.$AvatarPicturePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AvatarPictures.
   * @param {AvatarPictureCreateManyArgs} args - Arguments to create many AvatarPictures.
   * @example
   * // Create many AvatarPictures
   * const avatarPicture = await prisma.avatarPicture.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AvatarPictureCreateManyArgs>(args?: Prisma.SelectSubset<T, AvatarPictureCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AvatarPictures and returns the data saved in the database.
   * @param {AvatarPictureCreateManyAndReturnArgs} args - Arguments to create many AvatarPictures.
   * @example
   * // Create many AvatarPictures
   * const avatarPicture = await prisma.avatarPicture.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AvatarPictures and only return the `id`
   * const avatarPictureWithIdOnly = await prisma.avatarPicture.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AvatarPictureCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AvatarPictureCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AvatarPicturePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AvatarPicture.
   * @param {AvatarPictureDeleteArgs} args - Arguments to delete one AvatarPicture.
   * @example
   * // Delete one AvatarPicture
   * const AvatarPicture = await prisma.avatarPicture.delete({
   *   where: {
   *     // ... filter to delete one AvatarPicture
   *   }
   * })
   * 
   */
  delete<T extends AvatarPictureDeleteArgs>(args: Prisma.SelectSubset<T, AvatarPictureDeleteArgs<ExtArgs>>): Prisma.Prisma__AvatarPictureClient<runtime.Types.Result.GetResult<Prisma.$AvatarPicturePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AvatarPicture.
   * @param {AvatarPictureUpdateArgs} args - Arguments to update one AvatarPicture.
   * @example
   * // Update one AvatarPicture
   * const avatarPicture = await prisma.avatarPicture.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AvatarPictureUpdateArgs>(args: Prisma.SelectSubset<T, AvatarPictureUpdateArgs<ExtArgs>>): Prisma.Prisma__AvatarPictureClient<runtime.Types.Result.GetResult<Prisma.$AvatarPicturePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AvatarPictures.
   * @param {AvatarPictureDeleteManyArgs} args - Arguments to filter AvatarPictures to delete.
   * @example
   * // Delete a few AvatarPictures
   * const { count } = await prisma.avatarPicture.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AvatarPictureDeleteManyArgs>(args?: Prisma.SelectSubset<T, AvatarPictureDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AvatarPictures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvatarPictureUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AvatarPictures
   * const avatarPicture = await prisma.avatarPicture.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AvatarPictureUpdateManyArgs>(args: Prisma.SelectSubset<T, AvatarPictureUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AvatarPictures and returns the data updated in the database.
   * @param {AvatarPictureUpdateManyAndReturnArgs} args - Arguments to update many AvatarPictures.
   * @example
   * // Update many AvatarPictures
   * const avatarPicture = await prisma.avatarPicture.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AvatarPictures and only return the `id`
   * const avatarPictureWithIdOnly = await prisma.avatarPicture.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AvatarPictureUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AvatarPictureUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AvatarPicturePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AvatarPicture.
   * @param {AvatarPictureUpsertArgs} args - Arguments to update or create a AvatarPicture.
   * @example
   * // Update or create a AvatarPicture
   * const avatarPicture = await prisma.avatarPicture.upsert({
   *   create: {
   *     // ... data to create a AvatarPicture
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AvatarPicture we want to update
   *   }
   * })
   */
  upsert<T extends AvatarPictureUpsertArgs>(args: Prisma.SelectSubset<T, AvatarPictureUpsertArgs<ExtArgs>>): Prisma.Prisma__AvatarPictureClient<runtime.Types.Result.GetResult<Prisma.$AvatarPicturePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AvatarPictures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvatarPictureCountArgs} args - Arguments to filter AvatarPictures to count.
   * @example
   * // Count the number of AvatarPictures
   * const count = await prisma.avatarPicture.count({
   *   where: {
   *     // ... the filter for the AvatarPictures we want to count
   *   }
   * })
  **/
  count<T extends AvatarPictureCountArgs>(
    args?: Prisma.Subset<T, AvatarPictureCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AvatarPictureCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AvatarPicture.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvatarPictureAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AvatarPictureAggregateArgs>(args: Prisma.Subset<T, AvatarPictureAggregateArgs>): Prisma.PrismaPromise<GetAvatarPictureAggregateType<T>>

  /**
   * Group by AvatarPicture.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AvatarPictureGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AvatarPictureGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AvatarPictureGroupByArgs['orderBy'] }
      : { orderBy?: AvatarPictureGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AvatarPictureGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAvatarPictureGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AvatarPicture model
 */
readonly fields: AvatarPictureFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AvatarPicture.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AvatarPictureClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  by_profile<T extends Prisma.ProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AvatarPicture model
 */
export interface AvatarPictureFieldRefs {
  readonly id: Prisma.FieldRef<"AvatarPicture", 'String'>
  readonly created_at: Prisma.FieldRef<"AvatarPicture", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"AvatarPicture", 'DateTime'>
  readonly url: Prisma.FieldRef<"AvatarPicture", 'String'>
  readonly by_profile_id: Prisma.FieldRef<"AvatarPicture", 'String'>
}
    

// Custom InputTypes
/**
 * AvatarPicture findUnique
 */
export type AvatarPictureFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarPicture
   */
  select?: Prisma.AvatarPictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarPicture
   */
  omit?: Prisma.AvatarPictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarPictureInclude<ExtArgs> | null
  /**
   * Filter, which AvatarPicture to fetch.
   */
  where: Prisma.AvatarPictureWhereUniqueInput
}

/**
 * AvatarPicture findUniqueOrThrow
 */
export type AvatarPictureFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarPicture
   */
  select?: Prisma.AvatarPictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarPicture
   */
  omit?: Prisma.AvatarPictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarPictureInclude<ExtArgs> | null
  /**
   * Filter, which AvatarPicture to fetch.
   */
  where: Prisma.AvatarPictureWhereUniqueInput
}

/**
 * AvatarPicture findFirst
 */
export type AvatarPictureFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarPicture
   */
  select?: Prisma.AvatarPictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarPicture
   */
  omit?: Prisma.AvatarPictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarPictureInclude<ExtArgs> | null
  /**
   * Filter, which AvatarPicture to fetch.
   */
  where?: Prisma.AvatarPictureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AvatarPictures to fetch.
   */
  orderBy?: Prisma.AvatarPictureOrderByWithRelationInput | Prisma.AvatarPictureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AvatarPictures.
   */
  cursor?: Prisma.AvatarPictureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AvatarPictures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AvatarPictures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AvatarPictures.
   */
  distinct?: Prisma.AvatarPictureScalarFieldEnum | Prisma.AvatarPictureScalarFieldEnum[]
}

/**
 * AvatarPicture findFirstOrThrow
 */
export type AvatarPictureFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarPicture
   */
  select?: Prisma.AvatarPictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarPicture
   */
  omit?: Prisma.AvatarPictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarPictureInclude<ExtArgs> | null
  /**
   * Filter, which AvatarPicture to fetch.
   */
  where?: Prisma.AvatarPictureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AvatarPictures to fetch.
   */
  orderBy?: Prisma.AvatarPictureOrderByWithRelationInput | Prisma.AvatarPictureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AvatarPictures.
   */
  cursor?: Prisma.AvatarPictureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AvatarPictures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AvatarPictures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AvatarPictures.
   */
  distinct?: Prisma.AvatarPictureScalarFieldEnum | Prisma.AvatarPictureScalarFieldEnum[]
}

/**
 * AvatarPicture findMany
 */
export type AvatarPictureFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarPicture
   */
  select?: Prisma.AvatarPictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarPicture
   */
  omit?: Prisma.AvatarPictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarPictureInclude<ExtArgs> | null
  /**
   * Filter, which AvatarPictures to fetch.
   */
  where?: Prisma.AvatarPictureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AvatarPictures to fetch.
   */
  orderBy?: Prisma.AvatarPictureOrderByWithRelationInput | Prisma.AvatarPictureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AvatarPictures.
   */
  cursor?: Prisma.AvatarPictureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AvatarPictures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AvatarPictures.
   */
  skip?: number
  distinct?: Prisma.AvatarPictureScalarFieldEnum | Prisma.AvatarPictureScalarFieldEnum[]
}

/**
 * AvatarPicture create
 */
export type AvatarPictureCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarPicture
   */
  select?: Prisma.AvatarPictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarPicture
   */
  omit?: Prisma.AvatarPictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarPictureInclude<ExtArgs> | null
  /**
   * The data needed to create a AvatarPicture.
   */
  data: Prisma.XOR<Prisma.AvatarPictureCreateInput, Prisma.AvatarPictureUncheckedCreateInput>
}

/**
 * AvatarPicture createMany
 */
export type AvatarPictureCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AvatarPictures.
   */
  data: Prisma.AvatarPictureCreateManyInput | Prisma.AvatarPictureCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AvatarPicture createManyAndReturn
 */
export type AvatarPictureCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarPicture
   */
  select?: Prisma.AvatarPictureSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarPicture
   */
  omit?: Prisma.AvatarPictureOmit<ExtArgs> | null
  /**
   * The data used to create many AvatarPictures.
   */
  data: Prisma.AvatarPictureCreateManyInput | Prisma.AvatarPictureCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarPictureIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AvatarPicture update
 */
export type AvatarPictureUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarPicture
   */
  select?: Prisma.AvatarPictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarPicture
   */
  omit?: Prisma.AvatarPictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarPictureInclude<ExtArgs> | null
  /**
   * The data needed to update a AvatarPicture.
   */
  data: Prisma.XOR<Prisma.AvatarPictureUpdateInput, Prisma.AvatarPictureUncheckedUpdateInput>
  /**
   * Choose, which AvatarPicture to update.
   */
  where: Prisma.AvatarPictureWhereUniqueInput
}

/**
 * AvatarPicture updateMany
 */
export type AvatarPictureUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AvatarPictures.
   */
  data: Prisma.XOR<Prisma.AvatarPictureUpdateManyMutationInput, Prisma.AvatarPictureUncheckedUpdateManyInput>
  /**
   * Filter which AvatarPictures to update
   */
  where?: Prisma.AvatarPictureWhereInput
  /**
   * Limit how many AvatarPictures to update.
   */
  limit?: number
}

/**
 * AvatarPicture updateManyAndReturn
 */
export type AvatarPictureUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarPicture
   */
  select?: Prisma.AvatarPictureSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarPicture
   */
  omit?: Prisma.AvatarPictureOmit<ExtArgs> | null
  /**
   * The data used to update AvatarPictures.
   */
  data: Prisma.XOR<Prisma.AvatarPictureUpdateManyMutationInput, Prisma.AvatarPictureUncheckedUpdateManyInput>
  /**
   * Filter which AvatarPictures to update
   */
  where?: Prisma.AvatarPictureWhereInput
  /**
   * Limit how many AvatarPictures to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarPictureIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AvatarPicture upsert
 */
export type AvatarPictureUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarPicture
   */
  select?: Prisma.AvatarPictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarPicture
   */
  omit?: Prisma.AvatarPictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarPictureInclude<ExtArgs> | null
  /**
   * The filter to search for the AvatarPicture to update in case it exists.
   */
  where: Prisma.AvatarPictureWhereUniqueInput
  /**
   * In case the AvatarPicture found by the `where` argument doesn't exist, create a new AvatarPicture with this data.
   */
  create: Prisma.XOR<Prisma.AvatarPictureCreateInput, Prisma.AvatarPictureUncheckedCreateInput>
  /**
   * In case the AvatarPicture was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AvatarPictureUpdateInput, Prisma.AvatarPictureUncheckedUpdateInput>
}

/**
 * AvatarPicture delete
 */
export type AvatarPictureDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarPicture
   */
  select?: Prisma.AvatarPictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarPicture
   */
  omit?: Prisma.AvatarPictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarPictureInclude<ExtArgs> | null
  /**
   * Filter which AvatarPicture to delete.
   */
  where: Prisma.AvatarPictureWhereUniqueInput
}

/**
 * AvatarPicture deleteMany
 */
export type AvatarPictureDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AvatarPictures to delete
   */
  where?: Prisma.AvatarPictureWhereInput
  /**
   * Limit how many AvatarPictures to delete.
   */
  limit?: number
}

/**
 * AvatarPicture without action
 */
export type AvatarPictureDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarPicture
   */
  select?: Prisma.AvatarPictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarPicture
   */
  omit?: Prisma.AvatarPictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarPictureInclude<ExtArgs> | null
}
