/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck
/*
 * This file exports the `CoverPicture` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model CoverPicture
 *
 */
export type CoverPictureModel = runtime.Types.Result.DefaultSelection<Prisma.$CoverPicturePayload>;

export type AggregateCoverPicture = {
    _count: CoverPictureCountAggregateOutputType | null;
    _min: CoverPictureMinAggregateOutputType | null;
    _max: CoverPictureMaxAggregateOutputType | null;
};

export type CoverPictureMinAggregateOutputType = {
    id: string | null;
    created_at: Date | null;
    updated_at: Date | null;
    url: string | null;
    by_profile_id: string | null;
};

export type CoverPictureMaxAggregateOutputType = {
    id: string | null;
    created_at: Date | null;
    updated_at: Date | null;
    url: string | null;
    by_profile_id: string | null;
};

export type CoverPictureCountAggregateOutputType = {
    id: number;
    created_at: number;
    updated_at: number;
    url: number;
    by_profile_id: number;
    _all: number;
};

export type CoverPictureMinAggregateInputType = {
    id?: true;
    created_at?: true;
    updated_at?: true;
    url?: true;
    by_profile_id?: true;
};

export type CoverPictureMaxAggregateInputType = {
    id?: true;
    created_at?: true;
    updated_at?: true;
    url?: true;
    by_profile_id?: true;
};

export type CoverPictureCountAggregateInputType = {
    id?: true;
    created_at?: true;
    updated_at?: true;
    url?: true;
    by_profile_id?: true;
    _all?: true;
};

export type CoverPictureAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Filter which CoverPicture to aggregate.
     */
    where?: Prisma.CoverPictureWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of CoverPictures to fetch.
     */
    orderBy?: Prisma.CoverPictureOrderByWithRelationInput | Prisma.CoverPictureOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.CoverPictureWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` CoverPictures from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` CoverPictures.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned CoverPictures
     **/
    _count?: true | CoverPictureCountAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: CoverPictureMinAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: CoverPictureMaxAggregateInputType;
};

export type GetCoverPictureAggregateType<T extends CoverPictureAggregateArgs> = {
    [P in keyof T & keyof AggregateCoverPicture]: P extends "_count" | "count"
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateCoverPicture[P]>
        : Prisma.GetScalarType<T[P], AggregateCoverPicture[P]>;
};

export type CoverPictureGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    where?: Prisma.CoverPictureWhereInput;
    orderBy?: Prisma.CoverPictureOrderByWithAggregationInput | Prisma.CoverPictureOrderByWithAggregationInput[];
    by: Prisma.CoverPictureScalarFieldEnum[] | Prisma.CoverPictureScalarFieldEnum;
    having?: Prisma.CoverPictureScalarWhereWithAggregatesInput;
    take?: number;
    skip?: number;
    _count?: CoverPictureCountAggregateInputType | true;
    _min?: CoverPictureMinAggregateInputType;
    _max?: CoverPictureMaxAggregateInputType;
};

export type CoverPictureGroupByOutputType = {
    id: string;
    created_at: Date;
    updated_at: Date;
    url: string;
    by_profile_id: string;
    _count: CoverPictureCountAggregateOutputType | null;
    _min: CoverPictureMinAggregateOutputType | null;
    _max: CoverPictureMaxAggregateOutputType | null;
};

type GetCoverPictureGroupByPayload<T extends CoverPictureGroupByArgs> = Prisma.PrismaPromise<
    Array<
        Prisma.PickEnumerable<CoverPictureGroupByOutputType, T["by"]> & {
            [P in keyof T & keyof CoverPictureGroupByOutputType]: P extends "_count"
                ? T[P] extends boolean
                    ? number
                    : Prisma.GetScalarType<T[P], CoverPictureGroupByOutputType[P]>
                : Prisma.GetScalarType<T[P], CoverPictureGroupByOutputType[P]>;
        }
    >
>;

export type CoverPictureWhereInput = {
    AND?: Prisma.CoverPictureWhereInput | Prisma.CoverPictureWhereInput[];
    OR?: Prisma.CoverPictureWhereInput[];
    NOT?: Prisma.CoverPictureWhereInput | Prisma.CoverPictureWhereInput[];
    id?: Prisma.StringFilter<"CoverPicture"> | string;
    created_at?: Prisma.DateTimeFilter<"CoverPicture"> | Date | string;
    updated_at?: Prisma.DateTimeFilter<"CoverPicture"> | Date | string;
    url?: Prisma.StringFilter<"CoverPicture"> | string;
    by_profile_id?: Prisma.StringFilter<"CoverPicture"> | string;
    by_profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>;
};

export type CoverPictureOrderByWithRelationInput = {
    id?: Prisma.SortOrder;
    created_at?: Prisma.SortOrder;
    updated_at?: Prisma.SortOrder;
    url?: Prisma.SortOrder;
    by_profile_id?: Prisma.SortOrder;
    by_profile?: Prisma.ProfileOrderByWithRelationInput;
};

export type CoverPictureWhereUniqueInput = Prisma.AtLeast<
    {
        id?: string;
        by_profile_id?: string;
        AND?: Prisma.CoverPictureWhereInput | Prisma.CoverPictureWhereInput[];
        OR?: Prisma.CoverPictureWhereInput[];
        NOT?: Prisma.CoverPictureWhereInput | Prisma.CoverPictureWhereInput[];
        created_at?: Prisma.DateTimeFilter<"CoverPicture"> | Date | string;
        updated_at?: Prisma.DateTimeFilter<"CoverPicture"> | Date | string;
        url?: Prisma.StringFilter<"CoverPicture"> | string;
        by_profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>;
    },
    "id" | "by_profile_id"
>;

export type CoverPictureOrderByWithAggregationInput = {
    id?: Prisma.SortOrder;
    created_at?: Prisma.SortOrder;
    updated_at?: Prisma.SortOrder;
    url?: Prisma.SortOrder;
    by_profile_id?: Prisma.SortOrder;
    _count?: Prisma.CoverPictureCountOrderByAggregateInput;
    _max?: Prisma.CoverPictureMaxOrderByAggregateInput;
    _min?: Prisma.CoverPictureMinOrderByAggregateInput;
};

export type CoverPictureScalarWhereWithAggregatesInput = {
    AND?: Prisma.CoverPictureScalarWhereWithAggregatesInput | Prisma.CoverPictureScalarWhereWithAggregatesInput[];
    OR?: Prisma.CoverPictureScalarWhereWithAggregatesInput[];
    NOT?: Prisma.CoverPictureScalarWhereWithAggregatesInput | Prisma.CoverPictureScalarWhereWithAggregatesInput[];
    id?: Prisma.StringWithAggregatesFilter<"CoverPicture"> | string;
    created_at?: Prisma.DateTimeWithAggregatesFilter<"CoverPicture"> | Date | string;
    updated_at?: Prisma.DateTimeWithAggregatesFilter<"CoverPicture"> | Date | string;
    url?: Prisma.StringWithAggregatesFilter<"CoverPicture"> | string;
    by_profile_id?: Prisma.StringWithAggregatesFilter<"CoverPicture"> | string;
};

export type CoverPictureCreateInput = {
    id?: string;
    created_at?: Date | string;
    updated_at?: Date | string;
    url: string;
    by_profile: Prisma.ProfileCreateNestedOneWithoutCoverInput;
};

export type CoverPictureUncheckedCreateInput = {
    id?: string;
    created_at?: Date | string;
    updated_at?: Date | string;
    url: string;
    by_profile_id: string;
};

export type CoverPictureUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    url?: Prisma.StringFieldUpdateOperationsInput | string;
    by_profile?: Prisma.ProfileUpdateOneRequiredWithoutCoverNestedInput;
};

export type CoverPictureUncheckedUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    url?: Prisma.StringFieldUpdateOperationsInput | string;
    by_profile_id?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type CoverPictureCreateManyInput = {
    id?: string;
    created_at?: Date | string;
    updated_at?: Date | string;
    url: string;
    by_profile_id: string;
};

export type CoverPictureUpdateManyMutationInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    url?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type CoverPictureUncheckedUpdateManyInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    url?: Prisma.StringFieldUpdateOperationsInput | string;
    by_profile_id?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type CoverPictureCountOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    created_at?: Prisma.SortOrder;
    updated_at?: Prisma.SortOrder;
    url?: Prisma.SortOrder;
    by_profile_id?: Prisma.SortOrder;
};

export type CoverPictureMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    created_at?: Prisma.SortOrder;
    updated_at?: Prisma.SortOrder;
    url?: Prisma.SortOrder;
    by_profile_id?: Prisma.SortOrder;
};

export type CoverPictureMinOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    created_at?: Prisma.SortOrder;
    updated_at?: Prisma.SortOrder;
    url?: Prisma.SortOrder;
    by_profile_id?: Prisma.SortOrder;
};

export type CoverPictureNullableScalarRelationFilter = {
    is?: Prisma.CoverPictureWhereInput | null;
    isNot?: Prisma.CoverPictureWhereInput | null;
};

export type CoverPictureCreateNestedOneWithoutBy_profileInput = {
    create?: Prisma.XOR<Prisma.CoverPictureCreateWithoutBy_profileInput, Prisma.CoverPictureUncheckedCreateWithoutBy_profileInput>;
    connectOrCreate?: Prisma.CoverPictureCreateOrConnectWithoutBy_profileInput;
    connect?: Prisma.CoverPictureWhereUniqueInput;
};

export type CoverPictureUncheckedCreateNestedOneWithoutBy_profileInput = {
    create?: Prisma.XOR<Prisma.CoverPictureCreateWithoutBy_profileInput, Prisma.CoverPictureUncheckedCreateWithoutBy_profileInput>;
    connectOrCreate?: Prisma.CoverPictureCreateOrConnectWithoutBy_profileInput;
    connect?: Prisma.CoverPictureWhereUniqueInput;
};

export type CoverPictureUpdateOneWithoutBy_profileNestedInput = {
    create?: Prisma.XOR<Prisma.CoverPictureCreateWithoutBy_profileInput, Prisma.CoverPictureUncheckedCreateWithoutBy_profileInput>;
    connectOrCreate?: Prisma.CoverPictureCreateOrConnectWithoutBy_profileInput;
    upsert?: Prisma.CoverPictureUpsertWithoutBy_profileInput;
    disconnect?: Prisma.CoverPictureWhereInput | boolean;
    delete?: Prisma.CoverPictureWhereInput | boolean;
    connect?: Prisma.CoverPictureWhereUniqueInput;
    update?: Prisma.XOR<
        Prisma.XOR<Prisma.CoverPictureUpdateToOneWithWhereWithoutBy_profileInput, Prisma.CoverPictureUpdateWithoutBy_profileInput>,
        Prisma.CoverPictureUncheckedUpdateWithoutBy_profileInput
    >;
};

export type CoverPictureUncheckedUpdateOneWithoutBy_profileNestedInput = {
    create?: Prisma.XOR<Prisma.CoverPictureCreateWithoutBy_profileInput, Prisma.CoverPictureUncheckedCreateWithoutBy_profileInput>;
    connectOrCreate?: Prisma.CoverPictureCreateOrConnectWithoutBy_profileInput;
    upsert?: Prisma.CoverPictureUpsertWithoutBy_profileInput;
    disconnect?: Prisma.CoverPictureWhereInput | boolean;
    delete?: Prisma.CoverPictureWhereInput | boolean;
    connect?: Prisma.CoverPictureWhereUniqueInput;
    update?: Prisma.XOR<
        Prisma.XOR<Prisma.CoverPictureUpdateToOneWithWhereWithoutBy_profileInput, Prisma.CoverPictureUpdateWithoutBy_profileInput>,
        Prisma.CoverPictureUncheckedUpdateWithoutBy_profileInput
    >;
};

export type CoverPictureCreateWithoutBy_profileInput = {
    id?: string;
    created_at?: Date | string;
    updated_at?: Date | string;
    url: string;
};

export type CoverPictureUncheckedCreateWithoutBy_profileInput = {
    id?: string;
    created_at?: Date | string;
    updated_at?: Date | string;
    url: string;
};

export type CoverPictureCreateOrConnectWithoutBy_profileInput = {
    where: Prisma.CoverPictureWhereUniqueInput;
    create: Prisma.XOR<Prisma.CoverPictureCreateWithoutBy_profileInput, Prisma.CoverPictureUncheckedCreateWithoutBy_profileInput>;
};

export type CoverPictureUpsertWithoutBy_profileInput = {
    update: Prisma.XOR<Prisma.CoverPictureUpdateWithoutBy_profileInput, Prisma.CoverPictureUncheckedUpdateWithoutBy_profileInput>;
    create: Prisma.XOR<Prisma.CoverPictureCreateWithoutBy_profileInput, Prisma.CoverPictureUncheckedCreateWithoutBy_profileInput>;
    where?: Prisma.CoverPictureWhereInput;
};

export type CoverPictureUpdateToOneWithWhereWithoutBy_profileInput = {
    where?: Prisma.CoverPictureWhereInput;
    data: Prisma.XOR<Prisma.CoverPictureUpdateWithoutBy_profileInput, Prisma.CoverPictureUncheckedUpdateWithoutBy_profileInput>;
};

export type CoverPictureUpdateWithoutBy_profileInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    url?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type CoverPictureUncheckedUpdateWithoutBy_profileInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    url?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type CoverPictureSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
    runtime.Types.Extensions.GetSelect<
        {
            id?: boolean;
            created_at?: boolean;
            updated_at?: boolean;
            url?: boolean;
            by_profile_id?: boolean;
            by_profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
        },
        ExtArgs["result"]["coverPicture"]
    >;

export type CoverPictureSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
    runtime.Types.Extensions.GetSelect<
        {
            id?: boolean;
            created_at?: boolean;
            updated_at?: boolean;
            url?: boolean;
            by_profile_id?: boolean;
            by_profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
        },
        ExtArgs["result"]["coverPicture"]
    >;

export type CoverPictureSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
    runtime.Types.Extensions.GetSelect<
        {
            id?: boolean;
            created_at?: boolean;
            updated_at?: boolean;
            url?: boolean;
            by_profile_id?: boolean;
            by_profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
        },
        ExtArgs["result"]["coverPicture"]
    >;

export type CoverPictureSelectScalar = {
    id?: boolean;
    created_at?: boolean;
    updated_at?: boolean;
    url?: boolean;
    by_profile_id?: boolean;
};

export type CoverPictureOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
    runtime.Types.Extensions.GetOmit<"id" | "created_at" | "updated_at" | "url" | "by_profile_id", ExtArgs["result"]["coverPicture"]>;
export type CoverPictureInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    by_profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
};
export type CoverPictureIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    by_profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
};
export type CoverPictureIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    by_profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
};

export type $CoverPicturePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    name: "CoverPicture";
    objects: {
        by_profile: Prisma.$ProfilePayload<ExtArgs>;
    };
    scalars: runtime.Types.Extensions.GetPayloadResult<
        {
            id: string;
            created_at: Date;
            updated_at: Date;
            url: string;
            by_profile_id: string;
        },
        ExtArgs["result"]["coverPicture"]
    >;
    composites: {};
};

export type CoverPictureGetPayload<S extends boolean | null | undefined | CoverPictureDefaultArgs> = runtime.Types.Result.GetResult<
    Prisma.$CoverPicturePayload,
    S
>;

export type CoverPictureCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = Omit<
    CoverPictureFindManyArgs,
    "select" | "include" | "distinct" | "omit"
> & {
    select?: CoverPictureCountAggregateInputType | true;
};

export interface CoverPictureDelegate<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> {
    [K: symbol]: { types: Prisma.TypeMap<ExtArgs>["model"]["CoverPicture"]; meta: { name: "CoverPicture" } };
    /**
     * Find zero or one CoverPicture that matches the filter.
     * @param {CoverPictureFindUniqueArgs} args - Arguments to find a CoverPicture
     * @example
     * // Get one CoverPicture
     * const coverPicture = await prisma.coverPicture.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends CoverPictureFindUniqueArgs>(
        args: Prisma.SelectSubset<T, CoverPictureFindUniqueArgs<ExtArgs>>,
    ): Prisma.Prisma__CoverPictureClient<
        runtime.Types.Result.GetResult<Prisma.$CoverPicturePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find one CoverPicture that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {CoverPictureFindUniqueOrThrowArgs} args - Arguments to find a CoverPicture
     * @example
     * // Get one CoverPicture
     * const coverPicture = await prisma.coverPicture.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends CoverPictureFindUniqueOrThrowArgs>(
        args: Prisma.SelectSubset<T, CoverPictureFindUniqueOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__CoverPictureClient<
        runtime.Types.Result.GetResult<Prisma.$CoverPicturePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first CoverPicture that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CoverPictureFindFirstArgs} args - Arguments to find a CoverPicture
     * @example
     * // Get one CoverPicture
     * const coverPicture = await prisma.coverPicture.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends CoverPictureFindFirstArgs>(
        args?: Prisma.SelectSubset<T, CoverPictureFindFirstArgs<ExtArgs>>,
    ): Prisma.Prisma__CoverPictureClient<
        runtime.Types.Result.GetResult<Prisma.$CoverPicturePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first CoverPicture that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CoverPictureFindFirstOrThrowArgs} args - Arguments to find a CoverPicture
     * @example
     * // Get one CoverPicture
     * const coverPicture = await prisma.coverPicture.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends CoverPictureFindFirstOrThrowArgs>(
        args?: Prisma.SelectSubset<T, CoverPictureFindFirstOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__CoverPictureClient<
        runtime.Types.Result.GetResult<Prisma.$CoverPicturePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find zero or more CoverPictures that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CoverPictureFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all CoverPictures
     * const coverPictures = await prisma.coverPicture.findMany()
     *
     * // Get first 10 CoverPictures
     * const coverPictures = await prisma.coverPicture.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const coverPictureWithIdOnly = await prisma.coverPicture.findMany({ select: { id: true } })
     *
     */
    findMany<T extends CoverPictureFindManyArgs>(
        args?: Prisma.SelectSubset<T, CoverPictureFindManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoverPicturePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>;

    /**
     * Create a CoverPicture.
     * @param {CoverPictureCreateArgs} args - Arguments to create a CoverPicture.
     * @example
     * // Create one CoverPicture
     * const CoverPicture = await prisma.coverPicture.create({
     *   data: {
     *     // ... data to create a CoverPicture
     *   }
     * })
     *
     */
    create<T extends CoverPictureCreateArgs>(
        args: Prisma.SelectSubset<T, CoverPictureCreateArgs<ExtArgs>>,
    ): Prisma.Prisma__CoverPictureClient<
        runtime.Types.Result.GetResult<Prisma.$CoverPicturePayload<ExtArgs>, T, "create", GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Create many CoverPictures.
     * @param {CoverPictureCreateManyArgs} args - Arguments to create many CoverPictures.
     * @example
     * // Create many CoverPictures
     * const coverPicture = await prisma.coverPicture.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends CoverPictureCreateManyArgs>(
        args?: Prisma.SelectSubset<T, CoverPictureCreateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Create many CoverPictures and returns the data saved in the database.
     * @param {CoverPictureCreateManyAndReturnArgs} args - Arguments to create many CoverPictures.
     * @example
     * // Create many CoverPictures
     * const coverPicture = await prisma.coverPicture.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many CoverPictures and only return the `id`
     * const coverPictureWithIdOnly = await prisma.coverPicture.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends CoverPictureCreateManyAndReturnArgs>(
        args?: Prisma.SelectSubset<T, CoverPictureCreateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoverPicturePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>;

    /**
     * Delete a CoverPicture.
     * @param {CoverPictureDeleteArgs} args - Arguments to delete one CoverPicture.
     * @example
     * // Delete one CoverPicture
     * const CoverPicture = await prisma.coverPicture.delete({
     *   where: {
     *     // ... filter to delete one CoverPicture
     *   }
     * })
     *
     */
    delete<T extends CoverPictureDeleteArgs>(
        args: Prisma.SelectSubset<T, CoverPictureDeleteArgs<ExtArgs>>,
    ): Prisma.Prisma__CoverPictureClient<
        runtime.Types.Result.GetResult<Prisma.$CoverPicturePayload<ExtArgs>, T, "delete", GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Update one CoverPicture.
     * @param {CoverPictureUpdateArgs} args - Arguments to update one CoverPicture.
     * @example
     * // Update one CoverPicture
     * const coverPicture = await prisma.coverPicture.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends CoverPictureUpdateArgs>(
        args: Prisma.SelectSubset<T, CoverPictureUpdateArgs<ExtArgs>>,
    ): Prisma.Prisma__CoverPictureClient<
        runtime.Types.Result.GetResult<Prisma.$CoverPicturePayload<ExtArgs>, T, "update", GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Delete zero or more CoverPictures.
     * @param {CoverPictureDeleteManyArgs} args - Arguments to filter CoverPictures to delete.
     * @example
     * // Delete a few CoverPictures
     * const { count } = await prisma.coverPicture.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends CoverPictureDeleteManyArgs>(
        args?: Prisma.SelectSubset<T, CoverPictureDeleteManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more CoverPictures.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CoverPictureUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many CoverPictures
     * const coverPicture = await prisma.coverPicture.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends CoverPictureUpdateManyArgs>(
        args: Prisma.SelectSubset<T, CoverPictureUpdateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more CoverPictures and returns the data updated in the database.
     * @param {CoverPictureUpdateManyAndReturnArgs} args - Arguments to update many CoverPictures.
     * @example
     * // Update many CoverPictures
     * const coverPicture = await prisma.coverPicture.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more CoverPictures and only return the `id`
     * const coverPictureWithIdOnly = await prisma.coverPicture.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends CoverPictureUpdateManyAndReturnArgs>(
        args: Prisma.SelectSubset<T, CoverPictureUpdateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoverPicturePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>;

    /**
     * Create or update one CoverPicture.
     * @param {CoverPictureUpsertArgs} args - Arguments to update or create a CoverPicture.
     * @example
     * // Update or create a CoverPicture
     * const coverPicture = await prisma.coverPicture.upsert({
     *   create: {
     *     // ... data to create a CoverPicture
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the CoverPicture we want to update
     *   }
     * })
     */
    upsert<T extends CoverPictureUpsertArgs>(
        args: Prisma.SelectSubset<T, CoverPictureUpsertArgs<ExtArgs>>,
    ): Prisma.Prisma__CoverPictureClient<
        runtime.Types.Result.GetResult<Prisma.$CoverPicturePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Count the number of CoverPictures.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CoverPictureCountArgs} args - Arguments to filter CoverPictures to count.
     * @example
     * // Count the number of CoverPictures
     * const count = await prisma.coverPicture.count({
     *   where: {
     *     // ... the filter for the CoverPictures we want to count
     *   }
     * })
     **/
    count<T extends CoverPictureCountArgs>(
        args?: Prisma.Subset<T, CoverPictureCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<"select", any>
            ? T["select"] extends true
                ? number
                : Prisma.GetScalarType<T["select"], CoverPictureCountAggregateOutputType>
            : number
    >;

    /**
     * Allows you to perform aggregations operations on a CoverPicture.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CoverPictureAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends CoverPictureAggregateArgs>(
        args: Prisma.Subset<T, CoverPictureAggregateArgs>,
    ): Prisma.PrismaPromise<GetCoverPictureAggregateType<T>>;

    /**
     * Group by CoverPicture.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CoverPictureGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends CoverPictureGroupByArgs,
        HasSelectOrTake extends Prisma.Or<Prisma.Extends<"skip", Prisma.Keys<T>>, Prisma.Extends<"take", Prisma.Keys<T>>>,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: CoverPictureGroupByArgs["orderBy"] }
            : { orderBy?: CoverPictureGroupByArgs["orderBy"] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>>,
        ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T["having"]>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
            ? {
                  [P in HavingFields]: P extends ByFields
                      ? never
                      : P extends string
                      ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                      : [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
              }[HavingFields]
            : "take" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
                ? ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields]
                : 'Error: If you provide "take", you also need to provide "orderBy"'
            : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
                ? ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields]
                : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
            ? {}
            : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
    >(
        args: Prisma.SubsetIntersection<T, CoverPictureGroupByArgs, OrderByArg> & InputErrors,
    ): {} extends InputErrors ? GetCoverPictureGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
    /**
     * Fields of the CoverPicture model
     */
    readonly fields: CoverPictureFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CoverPicture.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CoverPictureClient<
    T,
    Null = never,
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: "PrismaPromise";
    by_profile<T extends Prisma.ProfileDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.ProfileDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__ProfileClient<
        runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(
        onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
        onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
    ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(
        onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
    ): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the CoverPicture model
 */
export interface CoverPictureFieldRefs {
    readonly id: Prisma.FieldRef<"CoverPicture", "String">;
    readonly created_at: Prisma.FieldRef<"CoverPicture", "DateTime">;
    readonly updated_at: Prisma.FieldRef<"CoverPicture", "DateTime">;
    readonly url: Prisma.FieldRef<"CoverPicture", "String">;
    readonly by_profile_id: Prisma.FieldRef<"CoverPicture", "String">;
}

// Custom InputTypes
/**
 * CoverPicture findUnique
 */
export type CoverPictureFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CoverPicture
     */
    select?: Prisma.CoverPictureSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CoverPicture
     */
    omit?: Prisma.CoverPictureOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CoverPictureInclude<ExtArgs> | null;
    /**
     * Filter, which CoverPicture to fetch.
     */
    where: Prisma.CoverPictureWhereUniqueInput;
};

/**
 * CoverPicture findUniqueOrThrow
 */
export type CoverPictureFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CoverPicture
     */
    select?: Prisma.CoverPictureSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CoverPicture
     */
    omit?: Prisma.CoverPictureOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CoverPictureInclude<ExtArgs> | null;
    /**
     * Filter, which CoverPicture to fetch.
     */
    where: Prisma.CoverPictureWhereUniqueInput;
};

/**
 * CoverPicture findFirst
 */
export type CoverPictureFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CoverPicture
     */
    select?: Prisma.CoverPictureSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CoverPicture
     */
    omit?: Prisma.CoverPictureOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CoverPictureInclude<ExtArgs> | null;
    /**
     * Filter, which CoverPicture to fetch.
     */
    where?: Prisma.CoverPictureWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of CoverPictures to fetch.
     */
    orderBy?: Prisma.CoverPictureOrderByWithRelationInput | Prisma.CoverPictureOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for CoverPictures.
     */
    cursor?: Prisma.CoverPictureWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` CoverPictures from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` CoverPictures.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of CoverPictures.
     */
    distinct?: Prisma.CoverPictureScalarFieldEnum | Prisma.CoverPictureScalarFieldEnum[];
};

/**
 * CoverPicture findFirstOrThrow
 */
export type CoverPictureFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CoverPicture
     */
    select?: Prisma.CoverPictureSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CoverPicture
     */
    omit?: Prisma.CoverPictureOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CoverPictureInclude<ExtArgs> | null;
    /**
     * Filter, which CoverPicture to fetch.
     */
    where?: Prisma.CoverPictureWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of CoverPictures to fetch.
     */
    orderBy?: Prisma.CoverPictureOrderByWithRelationInput | Prisma.CoverPictureOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for CoverPictures.
     */
    cursor?: Prisma.CoverPictureWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` CoverPictures from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` CoverPictures.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of CoverPictures.
     */
    distinct?: Prisma.CoverPictureScalarFieldEnum | Prisma.CoverPictureScalarFieldEnum[];
};

/**
 * CoverPicture findMany
 */
export type CoverPictureFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CoverPicture
     */
    select?: Prisma.CoverPictureSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CoverPicture
     */
    omit?: Prisma.CoverPictureOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CoverPictureInclude<ExtArgs> | null;
    /**
     * Filter, which CoverPictures to fetch.
     */
    where?: Prisma.CoverPictureWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of CoverPictures to fetch.
     */
    orderBy?: Prisma.CoverPictureOrderByWithRelationInput | Prisma.CoverPictureOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing CoverPictures.
     */
    cursor?: Prisma.CoverPictureWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` CoverPictures from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` CoverPictures.
     */
    skip?: number;
    distinct?: Prisma.CoverPictureScalarFieldEnum | Prisma.CoverPictureScalarFieldEnum[];
};

/**
 * CoverPicture create
 */
export type CoverPictureCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CoverPicture
     */
    select?: Prisma.CoverPictureSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CoverPicture
     */
    omit?: Prisma.CoverPictureOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CoverPictureInclude<ExtArgs> | null;
    /**
     * The data needed to create a CoverPicture.
     */
    data: Prisma.XOR<Prisma.CoverPictureCreateInput, Prisma.CoverPictureUncheckedCreateInput>;
};

/**
 * CoverPicture createMany
 */
export type CoverPictureCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * The data used to create many CoverPictures.
     */
    data: Prisma.CoverPictureCreateManyInput | Prisma.CoverPictureCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * CoverPicture createManyAndReturn
 */
export type CoverPictureCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CoverPicture
     */
    select?: Prisma.CoverPictureSelectCreateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the CoverPicture
     */
    omit?: Prisma.CoverPictureOmit<ExtArgs> | null;
    /**
     * The data used to create many CoverPictures.
     */
    data: Prisma.CoverPictureCreateManyInput | Prisma.CoverPictureCreateManyInput[];
    skipDuplicates?: boolean;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CoverPictureIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * CoverPicture update
 */
export type CoverPictureUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CoverPicture
     */
    select?: Prisma.CoverPictureSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CoverPicture
     */
    omit?: Prisma.CoverPictureOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CoverPictureInclude<ExtArgs> | null;
    /**
     * The data needed to update a CoverPicture.
     */
    data: Prisma.XOR<Prisma.CoverPictureUpdateInput, Prisma.CoverPictureUncheckedUpdateInput>;
    /**
     * Choose, which CoverPicture to update.
     */
    where: Prisma.CoverPictureWhereUniqueInput;
};

/**
 * CoverPicture updateMany
 */
export type CoverPictureUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * The data used to update CoverPictures.
     */
    data: Prisma.XOR<Prisma.CoverPictureUpdateManyMutationInput, Prisma.CoverPictureUncheckedUpdateManyInput>;
    /**
     * Filter which CoverPictures to update
     */
    where?: Prisma.CoverPictureWhereInput;
    /**
     * Limit how many CoverPictures to update.
     */
    limit?: number;
};

/**
 * CoverPicture updateManyAndReturn
 */
export type CoverPictureUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CoverPicture
     */
    select?: Prisma.CoverPictureSelectUpdateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the CoverPicture
     */
    omit?: Prisma.CoverPictureOmit<ExtArgs> | null;
    /**
     * The data used to update CoverPictures.
     */
    data: Prisma.XOR<Prisma.CoverPictureUpdateManyMutationInput, Prisma.CoverPictureUncheckedUpdateManyInput>;
    /**
     * Filter which CoverPictures to update
     */
    where?: Prisma.CoverPictureWhereInput;
    /**
     * Limit how many CoverPictures to update.
     */
    limit?: number;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CoverPictureIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * CoverPicture upsert
 */
export type CoverPictureUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CoverPicture
     */
    select?: Prisma.CoverPictureSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CoverPicture
     */
    omit?: Prisma.CoverPictureOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CoverPictureInclude<ExtArgs> | null;
    /**
     * The filter to search for the CoverPicture to update in case it exists.
     */
    where: Prisma.CoverPictureWhereUniqueInput;
    /**
     * In case the CoverPicture found by the `where` argument doesn't exist, create a new CoverPicture with this data.
     */
    create: Prisma.XOR<Prisma.CoverPictureCreateInput, Prisma.CoverPictureUncheckedCreateInput>;
    /**
     * In case the CoverPicture was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<Prisma.CoverPictureUpdateInput, Prisma.CoverPictureUncheckedUpdateInput>;
};

/**
 * CoverPicture delete
 */
export type CoverPictureDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CoverPicture
     */
    select?: Prisma.CoverPictureSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CoverPicture
     */
    omit?: Prisma.CoverPictureOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CoverPictureInclude<ExtArgs> | null;
    /**
     * Filter which CoverPicture to delete.
     */
    where: Prisma.CoverPictureWhereUniqueInput;
};

/**
 * CoverPicture deleteMany
 */
export type CoverPictureDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Filter which CoverPictures to delete
     */
    where?: Prisma.CoverPictureWhereInput;
    /**
     * Limit how many CoverPictures to delete.
     */
    limit?: number;
};

/**
 * CoverPicture without action
 */
export type CoverPictureDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CoverPicture
     */
    select?: Prisma.CoverPictureSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CoverPicture
     */
    omit?: Prisma.CoverPictureOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CoverPictureInclude<ExtArgs> | null;
};

