export const endpointsConfig = {
    administration: {
        getAllUsersInfo: "/get-all-users-info",
        baseUrl: "/administration",
    },
    authentication: {
        baseUrl: "/authentication",
        registration: "/registration",
        loginByEmail: "/login/by/email",
        loginByUsername: "/login/by/username",
        checkUsernameAvailability: <T extends string>(u: T) => `/check-username-availability/${u}` as const,
        checkSession: "/check-session",
        logout: "/logout",
    },
    userAccount: {
        baseUrl: "/user-account",
        exploreMe: "/explore/my-account",
        setEmail: "/set/email",
        updateEmail: "/update/email",
        updatePassword: "/update/password",
        updateUsername: <T extends string>(username: T) => `/update/username-to/${username}` as const,
        allSessions: "/get/all-sessions",
        terminateOtherSessions: "/sessions/terminate-other-sessions",
        terminateSpecificSession: <T extends string>(sessionId: T) => `/sessions/terminate-specific-session/${sessionId}` as const,
        deleteAccount: "/delete-account",
    },
    userProfile: {
        baseUrl: "/user-profile",
        exploreOthersProfile: <T extends string>(username: T) => `/explore/others-profile/${username}` as const,
        viewMyProfile: "/view/my-profile",
        updateBio: "/update/bio",
        updateNickname: <T extends string>(nickname: T) => `/update/nickname/to/${nickname}` as const,
    },
    commentAboutAnime: {
        baseUrl: "/comment-about-anime",
        allCommentsForAnime: <T extends string>(animeId: T) => `/get/all-comments-for-anime/${animeId}` as const,
        getAllMyComments: "/get/all-my-comments",
        getAllCommentsFromProfile: <T extends string>(username: T) => `/get/all-for-public-profile/${username}` as const,
        createComment: <T extends string>(animeId: T) => `/create/${animeId}` as const,
        updateComment: <T extends string>(commentId: T) => `/update/${commentId}` as const,
        deleteComment: <T extends string>(commentId: T) => `/delete/${commentId}` as const,
        reportTheComment: "/report-the-comment",
        addLike: <T extends string>(commentId: T) => `/add/like/${commentId}` as const,
        deleteLike: <T extends string>(commentId: T) => `/delete/like/${commentId}` as const,
        addDislike: <T extends string>(commentId: T) => `/add/dislike/${commentId}` as const,
        deleteDislike: <T extends string>(commentId: T) => `/delete/dislike/${commentId}` as const,
    },
    replyToComment: {
        baseUrl: "/reply-to-comment",
        getOneById: <T extends string>(replyId: T) => `/get/one/${replyId}` as const,
        getRepliesByCommentId: <T extends string>(commentId: T) => `/get/all/${commentId}` as const,
        createReply: "/create",
        editReply: "/edit",
        deleteReply: <T extends string>(replyId: T) => `/delete/${replyId}` as const,
        reportReply: <T extends string, U extends string>(type: T, replyId: U) => `/report/${type}/${replyId}` as const,
        addDislike: <T extends string>(replyId: T) => `/vote/add/dislike/${replyId}` as const,
        addLike: <T extends string>(replyId: T) => `/vote/add/like/${replyId}` as const,
        deleteDislike: <T extends string>(replyId: T) => `/vote/delete/dislike/${replyId}` as const,
        deleteLike: <T extends string>(replyId: T) => `/vote/delete/like/${replyId}` as const,
    },
    media: {
        baseUrl: "/media",
        setAvatar: "/avatar/set",
        updateAvatar: "/avatar/update",
        deleteAvatar: "/avatar/delete",
        viewAvatarByFs: "/avatar/view-fs",
        UPLOAD_IMAGE_FILENAME: "one_image_file",
    },
    animeBookmarks: {
        baseUrl: "/anime-bookmark-collection",
        getAllList: "/get/all-list",
        getStatusForAnime: <T extends string>(animeId: T) => `/get-status-for-one/${animeId}` as const,
        getListOfWatching: "/get/list/watching",
        getListOfAbandoned: "/get/list/abandoned",
        getListOfPlanned: "/get/list/planned",
        getListOfCompleted: "/get/list/completed",
        createWatching: <T extends string>(animeId: T) => `/add/watching/${animeId}` as const,
        createAbandoned: <T extends string>(animeId: T) => `/add/abandoned/${animeId}` as const,
        createPlanned: <T extends string>(animeId: T) => `/add/planned/${animeId}` as const,
        createCompleted: <T extends string>(animeId: T) => `/add/completed/${animeId}` as const,
        deleteWatching: <T extends string>(animeId: T) => `/delete/watching/${animeId}` as const,
        deleteAbandoned: <T extends string>(animeId: T) => `/delete/abandoned/${animeId}` as const,
        deletePlanned: <T extends string>(animeId: T) => `/delete/planned/${animeId}` as const,
        deleteCompleted: <T extends string>(animeId: T) => `/delete/completed/${animeId}` as const,
    },
    voteToAnime: {
        baseUrl: "/vote-to-anime",
        exploreLikes: "/get/explore/likes",
        exploreDislikes: "/get/explore/dislikes",
        viewVoteOnAnime: <T extends string>(animeId: T) => `/get/view/vote/${animeId}` as const,
        addLikeToAnime: <T extends string>(animeId: T) => `/add/like/${animeId}` as const,
        deleteLikeFromAnime: <T extends string>(animeId: T) => `/delete/like/${animeId}` as const,
        addDislikeToAnime: <T extends string>(animeId: T) => `/add/dislike/${animeId}` as const,
        deleteDislikeFromAnime: <T extends string>(animeId: T) => `/delete/dislike/${animeId}` as const,
    },
    ping: {
        baseUrl: "/ping",
        get: "/",
    },
} as const;
