
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  Account: 'Account',
  Session: 'Session',
  AvatarPicture: 'AvatarPicture',
  CoverPicture: 'CoverPicture',
  Profile: 'Profile',
  AnimeBookmark: 'AnimeBookmark',
  AnimeFavorite: 'AnimeFavorite',
  Reply: 'Reply',
  Comment: 'Comment',
  CommentVote: 'CommentVote',
  ReplyVote: 'ReplyVote'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AccountScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  type: 'type',
  email: 'email',
  username: 'username',
  password_hash: 'password_hash',
  is_activated: 'is_activated',
  activation_link: 'activation_link'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  token: 'token',
  created_at: 'created_at',
  updated_at: 'updated_at',
  expires_at: 'expires_at',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  by_account_id: 'by_account_id'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const AvatarPictureScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  url: 'url',
  by_profile_id: 'by_profile_id'
} as const

export type AvatarPictureScalarFieldEnum = (typeof AvatarPictureScalarFieldEnum)[keyof typeof AvatarPictureScalarFieldEnum]


export const CoverPictureScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  url: 'url',
  by_profile_id: 'by_profile_id'
} as const

export type CoverPictureScalarFieldEnum = (typeof CoverPictureScalarFieldEnum)[keyof typeof CoverPictureScalarFieldEnum]


export const ProfileScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  bio: 'bio',
  by_account_id: 'by_account_id',
  nickname: 'nickname'
} as const

export type ProfileScalarFieldEnum = (typeof ProfileScalarFieldEnum)[keyof typeof ProfileScalarFieldEnum]


export const AnimeBookmarkScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  profile_id: 'profile_id',
  anime_id: 'anime_id',
  status: 'status'
} as const

export type AnimeBookmarkScalarFieldEnum = (typeof AnimeBookmarkScalarFieldEnum)[keyof typeof AnimeBookmarkScalarFieldEnum]


export const AnimeFavoriteScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  profile_id: 'profile_id',
  anime_id: 'anime_id',
  vote: 'vote'
} as const

export type AnimeFavoriteScalarFieldEnum = (typeof AnimeFavoriteScalarFieldEnum)[keyof typeof AnimeFavoriteScalarFieldEnum]


export const ReplyScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  content: 'content',
  by_profile_id: 'by_profile_id',
  is_visible: 'is_visible',
  to_comment_id: 'to_comment_id'
} as const

export type ReplyScalarFieldEnum = (typeof ReplyScalarFieldEnum)[keyof typeof ReplyScalarFieldEnum]


export const CommentScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  content: 'content',
  is_visible: 'is_visible',
  by_profile_id: 'by_profile_id',
  anime_id: 'anime_id'
} as const

export type CommentScalarFieldEnum = (typeof CommentScalarFieldEnum)[keyof typeof CommentScalarFieldEnum]


export const CommentVoteScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  by_profile_id: 'by_profile_id',
  comment_id: 'comment_id',
  vote: 'vote'
} as const

export type CommentVoteScalarFieldEnum = (typeof CommentVoteScalarFieldEnum)[keyof typeof CommentVoteScalarFieldEnum]


export const ReplyVoteScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  by_profile_id: 'by_profile_id',
  reply_id: 'reply_id',
  vote: 'vote'
} as const

export type ReplyVoteScalarFieldEnum = (typeof ReplyVoteScalarFieldEnum)[keyof typeof ReplyVoteScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

